// Code generated by ent, DO NOT EDIT.

package subscriptionorder

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"github.com/Wei-Shaw/sub2api/ent/predicate"
)

// ID filters vertices based on their ID field.
func ID(id int64) predicate.SubscriptionOrder {
	return predicate.SubscriptionOrder(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id int64) predicate.SubscriptionOrder {
	return predicate.SubscriptionOrder(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id int64) predicate.SubscriptionOrder {
	return predicate.SubscriptionOrder(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...int64) predicate.SubscriptionOrder {
	return predicate.SubscriptionOrder(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...int64) predicate.SubscriptionOrder {
	return predicate.SubscriptionOrder(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id int64) predicate.SubscriptionOrder {
	return predicate.SubscriptionOrder(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id int64) predicate.SubscriptionOrder {
	return predicate.SubscriptionOrder(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id int64) predicate.SubscriptionOrder {
	return predicate.SubscriptionOrder(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id int64) predicate.SubscriptionOrder {
	return predicate.SubscriptionOrder(sql.FieldLTE(FieldID, id))
}

// CreatedAt applies equality check predicate on the "created_at" field. It's identical to CreatedAtEQ.
func CreatedAt(v time.Time) predicate.SubscriptionOrder {
	return predicate.SubscriptionOrder(sql.FieldEQ(FieldCreatedAt, v))
}

// UpdatedAt applies equality check predicate on the "updated_at" field. It's identical to UpdatedAtEQ.
func UpdatedAt(v time.Time) predicate.SubscriptionOrder {
	return predicate.SubscriptionOrder(sql.FieldEQ(FieldUpdatedAt, v))
}

// OrderNo applies equality check predicate on the "order_no" field. It's identical to OrderNoEQ.
func OrderNo(v string) predicate.SubscriptionOrder {
	return predicate.SubscriptionOrder(sql.FieldEQ(FieldOrderNo, v))
}

// UserID applies equality check predicate on the "user_id" field. It's identical to UserIDEQ.
func UserID(v int64) predicate.SubscriptionOrder {
	return predicate.SubscriptionOrder(sql.FieldEQ(FieldUserID, v))
}

// GroupID applies equality check predicate on the "group_id" field. It's identical to GroupIDEQ.
func GroupID(v int64) predicate.SubscriptionOrder {
	return predicate.SubscriptionOrder(sql.FieldEQ(FieldGroupID, v))
}

// SubscriptionID applies equality check predicate on the "subscription_id" field. It's identical to SubscriptionIDEQ.
func SubscriptionID(v int64) predicate.SubscriptionOrder {
	return predicate.SubscriptionOrder(sql.FieldEQ(FieldSubscriptionID, v))
}

// PaymentProvider applies equality check predicate on the "payment_provider" field. It's identical to PaymentProviderEQ.
func PaymentProvider(v string) predicate.SubscriptionOrder {
	return predicate.SubscriptionOrder(sql.FieldEQ(FieldPaymentProvider, v))
}

// PaymentURL applies equality check predicate on the "payment_url" field. It's identical to PaymentURLEQ.
func PaymentURL(v string) predicate.SubscriptionOrder {
	return predicate.SubscriptionOrder(sql.FieldEQ(FieldPaymentURL, v))
}

// PaymentQrcode applies equality check predicate on the "payment_qrcode" field. It's identical to PaymentQrcodeEQ.
func PaymentQrcode(v string) predicate.SubscriptionOrder {
	return predicate.SubscriptionOrder(sql.FieldEQ(FieldPaymentQrcode, v))
}

// PaymentOpenOrderID applies equality check predicate on the "payment_open_order_id" field. It's identical to PaymentOpenOrderIDEQ.
func PaymentOpenOrderID(v string) predicate.SubscriptionOrder {
	return predicate.SubscriptionOrder(sql.FieldEQ(FieldPaymentOpenOrderID, v))
}

// PaymentTransactionID applies equality check predicate on the "payment_transaction_id" field. It's identical to PaymentTransactionIDEQ.
func PaymentTransactionID(v string) predicate.SubscriptionOrder {
	return predicate.SubscriptionOrder(sql.FieldEQ(FieldPaymentTransactionID, v))
}

// PaymentPlugin applies equality check predicate on the "payment_plugin" field. It's identical to PaymentPluginEQ.
func PaymentPlugin(v string) predicate.SubscriptionOrder {
	return predicate.SubscriptionOrder(sql.FieldEQ(FieldPaymentPlugin, v))
}

// Status applies equality check predicate on the "status" field. It's identical to StatusEQ.
func Status(v string) predicate.SubscriptionOrder {
	return predicate.SubscriptionOrder(sql.FieldEQ(FieldStatus, v))
}

// Amount applies equality check predicate on the "amount" field. It's identical to AmountEQ.
func Amount(v float64) predicate.SubscriptionOrder {
	return predicate.SubscriptionOrder(sql.FieldEQ(FieldAmount, v))
}

// Currency applies equality check predicate on the "currency" field. It's identical to CurrencyEQ.
func Currency(v string) predicate.SubscriptionOrder {
	return predicate.SubscriptionOrder(sql.FieldEQ(FieldCurrency, v))
}

// ValidityDays applies equality check predicate on the "validity_days" field. It's identical to ValidityDaysEQ.
func ValidityDays(v int) predicate.SubscriptionOrder {
	return predicate.SubscriptionOrder(sql.FieldEQ(FieldValidityDays, v))
}

// PaidAt applies equality check predicate on the "paid_at" field. It's identical to PaidAtEQ.
func PaidAt(v time.Time) predicate.SubscriptionOrder {
	return predicate.SubscriptionOrder(sql.FieldEQ(FieldPaidAt, v))
}

// CanceledAt applies equality check predicate on the "canceled_at" field. It's identical to CanceledAtEQ.
func CanceledAt(v time.Time) predicate.SubscriptionOrder {
	return predicate.SubscriptionOrder(sql.FieldEQ(FieldCanceledAt, v))
}

// Notes applies equality check predicate on the "notes" field. It's identical to NotesEQ.
func Notes(v string) predicate.SubscriptionOrder {
	return predicate.SubscriptionOrder(sql.FieldEQ(FieldNotes, v))
}

// CreatedAtEQ applies the EQ predicate on the "created_at" field.
func CreatedAtEQ(v time.Time) predicate.SubscriptionOrder {
	return predicate.SubscriptionOrder(sql.FieldEQ(FieldCreatedAt, v))
}

// CreatedAtNEQ applies the NEQ predicate on the "created_at" field.
func CreatedAtNEQ(v time.Time) predicate.SubscriptionOrder {
	return predicate.SubscriptionOrder(sql.FieldNEQ(FieldCreatedAt, v))
}

// CreatedAtIn applies the In predicate on the "created_at" field.
func CreatedAtIn(vs ...time.Time) predicate.SubscriptionOrder {
	return predicate.SubscriptionOrder(sql.FieldIn(FieldCreatedAt, vs...))
}

// CreatedAtNotIn applies the NotIn predicate on the "created_at" field.
func CreatedAtNotIn(vs ...time.Time) predicate.SubscriptionOrder {
	return predicate.SubscriptionOrder(sql.FieldNotIn(FieldCreatedAt, vs...))
}

// CreatedAtGT applies the GT predicate on the "created_at" field.
func CreatedAtGT(v time.Time) predicate.SubscriptionOrder {
	return predicate.SubscriptionOrder(sql.FieldGT(FieldCreatedAt, v))
}

// CreatedAtGTE applies the GTE predicate on the "created_at" field.
func CreatedAtGTE(v time.Time) predicate.SubscriptionOrder {
	return predicate.SubscriptionOrder(sql.FieldGTE(FieldCreatedAt, v))
}

// CreatedAtLT applies the LT predicate on the "created_at" field.
func CreatedAtLT(v time.Time) predicate.SubscriptionOrder {
	return predicate.SubscriptionOrder(sql.FieldLT(FieldCreatedAt, v))
}

// CreatedAtLTE applies the LTE predicate on the "created_at" field.
func CreatedAtLTE(v time.Time) predicate.SubscriptionOrder {
	return predicate.SubscriptionOrder(sql.FieldLTE(FieldCreatedAt, v))
}

// UpdatedAtEQ applies the EQ predicate on the "updated_at" field.
func UpdatedAtEQ(v time.Time) predicate.SubscriptionOrder {
	return predicate.SubscriptionOrder(sql.FieldEQ(FieldUpdatedAt, v))
}

// UpdatedAtNEQ applies the NEQ predicate on the "updated_at" field.
func UpdatedAtNEQ(v time.Time) predicate.SubscriptionOrder {
	return predicate.SubscriptionOrder(sql.FieldNEQ(FieldUpdatedAt, v))
}

// UpdatedAtIn applies the In predicate on the "updated_at" field.
func UpdatedAtIn(vs ...time.Time) predicate.SubscriptionOrder {
	return predicate.SubscriptionOrder(sql.FieldIn(FieldUpdatedAt, vs...))
}

// UpdatedAtNotIn applies the NotIn predicate on the "updated_at" field.
func UpdatedAtNotIn(vs ...time.Time) predicate.SubscriptionOrder {
	return predicate.SubscriptionOrder(sql.FieldNotIn(FieldUpdatedAt, vs...))
}

// UpdatedAtGT applies the GT predicate on the "updated_at" field.
func UpdatedAtGT(v time.Time) predicate.SubscriptionOrder {
	return predicate.SubscriptionOrder(sql.FieldGT(FieldUpdatedAt, v))
}

// UpdatedAtGTE applies the GTE predicate on the "updated_at" field.
func UpdatedAtGTE(v time.Time) predicate.SubscriptionOrder {
	return predicate.SubscriptionOrder(sql.FieldGTE(FieldUpdatedAt, v))
}

// UpdatedAtLT applies the LT predicate on the "updated_at" field.
func UpdatedAtLT(v time.Time) predicate.SubscriptionOrder {
	return predicate.SubscriptionOrder(sql.FieldLT(FieldUpdatedAt, v))
}

// UpdatedAtLTE applies the LTE predicate on the "updated_at" field.
func UpdatedAtLTE(v time.Time) predicate.SubscriptionOrder {
	return predicate.SubscriptionOrder(sql.FieldLTE(FieldUpdatedAt, v))
}

// OrderNoEQ applies the EQ predicate on the "order_no" field.
func OrderNoEQ(v string) predicate.SubscriptionOrder {
	return predicate.SubscriptionOrder(sql.FieldEQ(FieldOrderNo, v))
}

// OrderNoNEQ applies the NEQ predicate on the "order_no" field.
func OrderNoNEQ(v string) predicate.SubscriptionOrder {
	return predicate.SubscriptionOrder(sql.FieldNEQ(FieldOrderNo, v))
}

// OrderNoIn applies the In predicate on the "order_no" field.
func OrderNoIn(vs ...string) predicate.SubscriptionOrder {
	return predicate.SubscriptionOrder(sql.FieldIn(FieldOrderNo, vs...))
}

// OrderNoNotIn applies the NotIn predicate on the "order_no" field.
func OrderNoNotIn(vs ...string) predicate.SubscriptionOrder {
	return predicate.SubscriptionOrder(sql.FieldNotIn(FieldOrderNo, vs...))
}

// OrderNoGT applies the GT predicate on the "order_no" field.
func OrderNoGT(v string) predicate.SubscriptionOrder {
	return predicate.SubscriptionOrder(sql.FieldGT(FieldOrderNo, v))
}

// OrderNoGTE applies the GTE predicate on the "order_no" field.
func OrderNoGTE(v string) predicate.SubscriptionOrder {
	return predicate.SubscriptionOrder(sql.FieldGTE(FieldOrderNo, v))
}

// OrderNoLT applies the LT predicate on the "order_no" field.
func OrderNoLT(v string) predicate.SubscriptionOrder {
	return predicate.SubscriptionOrder(sql.FieldLT(FieldOrderNo, v))
}

// OrderNoLTE applies the LTE predicate on the "order_no" field.
func OrderNoLTE(v string) predicate.SubscriptionOrder {
	return predicate.SubscriptionOrder(sql.FieldLTE(FieldOrderNo, v))
}

// OrderNoContains applies the Contains predicate on the "order_no" field.
func OrderNoContains(v string) predicate.SubscriptionOrder {
	return predicate.SubscriptionOrder(sql.FieldContains(FieldOrderNo, v))
}

// OrderNoHasPrefix applies the HasPrefix predicate on the "order_no" field.
func OrderNoHasPrefix(v string) predicate.SubscriptionOrder {
	return predicate.SubscriptionOrder(sql.FieldHasPrefix(FieldOrderNo, v))
}

// OrderNoHasSuffix applies the HasSuffix predicate on the "order_no" field.
func OrderNoHasSuffix(v string) predicate.SubscriptionOrder {
	return predicate.SubscriptionOrder(sql.FieldHasSuffix(FieldOrderNo, v))
}

// OrderNoEqualFold applies the EqualFold predicate on the "order_no" field.
func OrderNoEqualFold(v string) predicate.SubscriptionOrder {
	return predicate.SubscriptionOrder(sql.FieldEqualFold(FieldOrderNo, v))
}

// OrderNoContainsFold applies the ContainsFold predicate on the "order_no" field.
func OrderNoContainsFold(v string) predicate.SubscriptionOrder {
	return predicate.SubscriptionOrder(sql.FieldContainsFold(FieldOrderNo, v))
}

// UserIDEQ applies the EQ predicate on the "user_id" field.
func UserIDEQ(v int64) predicate.SubscriptionOrder {
	return predicate.SubscriptionOrder(sql.FieldEQ(FieldUserID, v))
}

// UserIDNEQ applies the NEQ predicate on the "user_id" field.
func UserIDNEQ(v int64) predicate.SubscriptionOrder {
	return predicate.SubscriptionOrder(sql.FieldNEQ(FieldUserID, v))
}

// UserIDIn applies the In predicate on the "user_id" field.
func UserIDIn(vs ...int64) predicate.SubscriptionOrder {
	return predicate.SubscriptionOrder(sql.FieldIn(FieldUserID, vs...))
}

// UserIDNotIn applies the NotIn predicate on the "user_id" field.
func UserIDNotIn(vs ...int64) predicate.SubscriptionOrder {
	return predicate.SubscriptionOrder(sql.FieldNotIn(FieldUserID, vs...))
}

// GroupIDEQ applies the EQ predicate on the "group_id" field.
func GroupIDEQ(v int64) predicate.SubscriptionOrder {
	return predicate.SubscriptionOrder(sql.FieldEQ(FieldGroupID, v))
}

// GroupIDNEQ applies the NEQ predicate on the "group_id" field.
func GroupIDNEQ(v int64) predicate.SubscriptionOrder {
	return predicate.SubscriptionOrder(sql.FieldNEQ(FieldGroupID, v))
}

// GroupIDIn applies the In predicate on the "group_id" field.
func GroupIDIn(vs ...int64) predicate.SubscriptionOrder {
	return predicate.SubscriptionOrder(sql.FieldIn(FieldGroupID, vs...))
}

// GroupIDNotIn applies the NotIn predicate on the "group_id" field.
func GroupIDNotIn(vs ...int64) predicate.SubscriptionOrder {
	return predicate.SubscriptionOrder(sql.FieldNotIn(FieldGroupID, vs...))
}

// SubscriptionIDEQ applies the EQ predicate on the "subscription_id" field.
func SubscriptionIDEQ(v int64) predicate.SubscriptionOrder {
	return predicate.SubscriptionOrder(sql.FieldEQ(FieldSubscriptionID, v))
}

// SubscriptionIDNEQ applies the NEQ predicate on the "subscription_id" field.
func SubscriptionIDNEQ(v int64) predicate.SubscriptionOrder {
	return predicate.SubscriptionOrder(sql.FieldNEQ(FieldSubscriptionID, v))
}

// SubscriptionIDIn applies the In predicate on the "subscription_id" field.
func SubscriptionIDIn(vs ...int64) predicate.SubscriptionOrder {
	return predicate.SubscriptionOrder(sql.FieldIn(FieldSubscriptionID, vs...))
}

// SubscriptionIDNotIn applies the NotIn predicate on the "subscription_id" field.
func SubscriptionIDNotIn(vs ...int64) predicate.SubscriptionOrder {
	return predicate.SubscriptionOrder(sql.FieldNotIn(FieldSubscriptionID, vs...))
}

// SubscriptionIDIsNil applies the IsNil predicate on the "subscription_id" field.
func SubscriptionIDIsNil() predicate.SubscriptionOrder {
	return predicate.SubscriptionOrder(sql.FieldIsNull(FieldSubscriptionID))
}

// SubscriptionIDNotNil applies the NotNil predicate on the "subscription_id" field.
func SubscriptionIDNotNil() predicate.SubscriptionOrder {
	return predicate.SubscriptionOrder(sql.FieldNotNull(FieldSubscriptionID))
}

// PaymentProviderEQ applies the EQ predicate on the "payment_provider" field.
func PaymentProviderEQ(v string) predicate.SubscriptionOrder {
	return predicate.SubscriptionOrder(sql.FieldEQ(FieldPaymentProvider, v))
}

// PaymentProviderNEQ applies the NEQ predicate on the "payment_provider" field.
func PaymentProviderNEQ(v string) predicate.SubscriptionOrder {
	return predicate.SubscriptionOrder(sql.FieldNEQ(FieldPaymentProvider, v))
}

// PaymentProviderIn applies the In predicate on the "payment_provider" field.
func PaymentProviderIn(vs ...string) predicate.SubscriptionOrder {
	return predicate.SubscriptionOrder(sql.FieldIn(FieldPaymentProvider, vs...))
}

// PaymentProviderNotIn applies the NotIn predicate on the "payment_provider" field.
func PaymentProviderNotIn(vs ...string) predicate.SubscriptionOrder {
	return predicate.SubscriptionOrder(sql.FieldNotIn(FieldPaymentProvider, vs...))
}

// PaymentProviderGT applies the GT predicate on the "payment_provider" field.
func PaymentProviderGT(v string) predicate.SubscriptionOrder {
	return predicate.SubscriptionOrder(sql.FieldGT(FieldPaymentProvider, v))
}

// PaymentProviderGTE applies the GTE predicate on the "payment_provider" field.
func PaymentProviderGTE(v string) predicate.SubscriptionOrder {
	return predicate.SubscriptionOrder(sql.FieldGTE(FieldPaymentProvider, v))
}

// PaymentProviderLT applies the LT predicate on the "payment_provider" field.
func PaymentProviderLT(v string) predicate.SubscriptionOrder {
	return predicate.SubscriptionOrder(sql.FieldLT(FieldPaymentProvider, v))
}

// PaymentProviderLTE applies the LTE predicate on the "payment_provider" field.
func PaymentProviderLTE(v string) predicate.SubscriptionOrder {
	return predicate.SubscriptionOrder(sql.FieldLTE(FieldPaymentProvider, v))
}

// PaymentProviderContains applies the Contains predicate on the "payment_provider" field.
func PaymentProviderContains(v string) predicate.SubscriptionOrder {
	return predicate.SubscriptionOrder(sql.FieldContains(FieldPaymentProvider, v))
}

// PaymentProviderHasPrefix applies the HasPrefix predicate on the "payment_provider" field.
func PaymentProviderHasPrefix(v string) predicate.SubscriptionOrder {
	return predicate.SubscriptionOrder(sql.FieldHasPrefix(FieldPaymentProvider, v))
}

// PaymentProviderHasSuffix applies the HasSuffix predicate on the "payment_provider" field.
func PaymentProviderHasSuffix(v string) predicate.SubscriptionOrder {
	return predicate.SubscriptionOrder(sql.FieldHasSuffix(FieldPaymentProvider, v))
}

// PaymentProviderEqualFold applies the EqualFold predicate on the "payment_provider" field.
func PaymentProviderEqualFold(v string) predicate.SubscriptionOrder {
	return predicate.SubscriptionOrder(sql.FieldEqualFold(FieldPaymentProvider, v))
}

// PaymentProviderContainsFold applies the ContainsFold predicate on the "payment_provider" field.
func PaymentProviderContainsFold(v string) predicate.SubscriptionOrder {
	return predicate.SubscriptionOrder(sql.FieldContainsFold(FieldPaymentProvider, v))
}

// PaymentURLEQ applies the EQ predicate on the "payment_url" field.
func PaymentURLEQ(v string) predicate.SubscriptionOrder {
	return predicate.SubscriptionOrder(sql.FieldEQ(FieldPaymentURL, v))
}

// PaymentURLNEQ applies the NEQ predicate on the "payment_url" field.
func PaymentURLNEQ(v string) predicate.SubscriptionOrder {
	return predicate.SubscriptionOrder(sql.FieldNEQ(FieldPaymentURL, v))
}

// PaymentURLIn applies the In predicate on the "payment_url" field.
func PaymentURLIn(vs ...string) predicate.SubscriptionOrder {
	return predicate.SubscriptionOrder(sql.FieldIn(FieldPaymentURL, vs...))
}

// PaymentURLNotIn applies the NotIn predicate on the "payment_url" field.
func PaymentURLNotIn(vs ...string) predicate.SubscriptionOrder {
	return predicate.SubscriptionOrder(sql.FieldNotIn(FieldPaymentURL, vs...))
}

// PaymentURLGT applies the GT predicate on the "payment_url" field.
func PaymentURLGT(v string) predicate.SubscriptionOrder {
	return predicate.SubscriptionOrder(sql.FieldGT(FieldPaymentURL, v))
}

// PaymentURLGTE applies the GTE predicate on the "payment_url" field.
func PaymentURLGTE(v string) predicate.SubscriptionOrder {
	return predicate.SubscriptionOrder(sql.FieldGTE(FieldPaymentURL, v))
}

// PaymentURLLT applies the LT predicate on the "payment_url" field.
func PaymentURLLT(v string) predicate.SubscriptionOrder {
	return predicate.SubscriptionOrder(sql.FieldLT(FieldPaymentURL, v))
}

// PaymentURLLTE applies the LTE predicate on the "payment_url" field.
func PaymentURLLTE(v string) predicate.SubscriptionOrder {
	return predicate.SubscriptionOrder(sql.FieldLTE(FieldPaymentURL, v))
}

// PaymentURLContains applies the Contains predicate on the "payment_url" field.
func PaymentURLContains(v string) predicate.SubscriptionOrder {
	return predicate.SubscriptionOrder(sql.FieldContains(FieldPaymentURL, v))
}

// PaymentURLHasPrefix applies the HasPrefix predicate on the "payment_url" field.
func PaymentURLHasPrefix(v string) predicate.SubscriptionOrder {
	return predicate.SubscriptionOrder(sql.FieldHasPrefix(FieldPaymentURL, v))
}

// PaymentURLHasSuffix applies the HasSuffix predicate on the "payment_url" field.
func PaymentURLHasSuffix(v string) predicate.SubscriptionOrder {
	return predicate.SubscriptionOrder(sql.FieldHasSuffix(FieldPaymentURL, v))
}

// PaymentURLIsNil applies the IsNil predicate on the "payment_url" field.
func PaymentURLIsNil() predicate.SubscriptionOrder {
	return predicate.SubscriptionOrder(sql.FieldIsNull(FieldPaymentURL))
}

// PaymentURLNotNil applies the NotNil predicate on the "payment_url" field.
func PaymentURLNotNil() predicate.SubscriptionOrder {
	return predicate.SubscriptionOrder(sql.FieldNotNull(FieldPaymentURL))
}

// PaymentURLEqualFold applies the EqualFold predicate on the "payment_url" field.
func PaymentURLEqualFold(v string) predicate.SubscriptionOrder {
	return predicate.SubscriptionOrder(sql.FieldEqualFold(FieldPaymentURL, v))
}

// PaymentURLContainsFold applies the ContainsFold predicate on the "payment_url" field.
func PaymentURLContainsFold(v string) predicate.SubscriptionOrder {
	return predicate.SubscriptionOrder(sql.FieldContainsFold(FieldPaymentURL, v))
}

// PaymentQrcodeEQ applies the EQ predicate on the "payment_qrcode" field.
func PaymentQrcodeEQ(v string) predicate.SubscriptionOrder {
	return predicate.SubscriptionOrder(sql.FieldEQ(FieldPaymentQrcode, v))
}

// PaymentQrcodeNEQ applies the NEQ predicate on the "payment_qrcode" field.
func PaymentQrcodeNEQ(v string) predicate.SubscriptionOrder {
	return predicate.SubscriptionOrder(sql.FieldNEQ(FieldPaymentQrcode, v))
}

// PaymentQrcodeIn applies the In predicate on the "payment_qrcode" field.
func PaymentQrcodeIn(vs ...string) predicate.SubscriptionOrder {
	return predicate.SubscriptionOrder(sql.FieldIn(FieldPaymentQrcode, vs...))
}

// PaymentQrcodeNotIn applies the NotIn predicate on the "payment_qrcode" field.
func PaymentQrcodeNotIn(vs ...string) predicate.SubscriptionOrder {
	return predicate.SubscriptionOrder(sql.FieldNotIn(FieldPaymentQrcode, vs...))
}

// PaymentQrcodeGT applies the GT predicate on the "payment_qrcode" field.
func PaymentQrcodeGT(v string) predicate.SubscriptionOrder {
	return predicate.SubscriptionOrder(sql.FieldGT(FieldPaymentQrcode, v))
}

// PaymentQrcodeGTE applies the GTE predicate on the "payment_qrcode" field.
func PaymentQrcodeGTE(v string) predicate.SubscriptionOrder {
	return predicate.SubscriptionOrder(sql.FieldGTE(FieldPaymentQrcode, v))
}

// PaymentQrcodeLT applies the LT predicate on the "payment_qrcode" field.
func PaymentQrcodeLT(v string) predicate.SubscriptionOrder {
	return predicate.SubscriptionOrder(sql.FieldLT(FieldPaymentQrcode, v))
}

// PaymentQrcodeLTE applies the LTE predicate on the "payment_qrcode" field.
func PaymentQrcodeLTE(v string) predicate.SubscriptionOrder {
	return predicate.SubscriptionOrder(sql.FieldLTE(FieldPaymentQrcode, v))
}

// PaymentQrcodeContains applies the Contains predicate on the "payment_qrcode" field.
func PaymentQrcodeContains(v string) predicate.SubscriptionOrder {
	return predicate.SubscriptionOrder(sql.FieldContains(FieldPaymentQrcode, v))
}

// PaymentQrcodeHasPrefix applies the HasPrefix predicate on the "payment_qrcode" field.
func PaymentQrcodeHasPrefix(v string) predicate.SubscriptionOrder {
	return predicate.SubscriptionOrder(sql.FieldHasPrefix(FieldPaymentQrcode, v))
}

// PaymentQrcodeHasSuffix applies the HasSuffix predicate on the "payment_qrcode" field.
func PaymentQrcodeHasSuffix(v string) predicate.SubscriptionOrder {
	return predicate.SubscriptionOrder(sql.FieldHasSuffix(FieldPaymentQrcode, v))
}

// PaymentQrcodeIsNil applies the IsNil predicate on the "payment_qrcode" field.
func PaymentQrcodeIsNil() predicate.SubscriptionOrder {
	return predicate.SubscriptionOrder(sql.FieldIsNull(FieldPaymentQrcode))
}

// PaymentQrcodeNotNil applies the NotNil predicate on the "payment_qrcode" field.
func PaymentQrcodeNotNil() predicate.SubscriptionOrder {
	return predicate.SubscriptionOrder(sql.FieldNotNull(FieldPaymentQrcode))
}

// PaymentQrcodeEqualFold applies the EqualFold predicate on the "payment_qrcode" field.
func PaymentQrcodeEqualFold(v string) predicate.SubscriptionOrder {
	return predicate.SubscriptionOrder(sql.FieldEqualFold(FieldPaymentQrcode, v))
}

// PaymentQrcodeContainsFold applies the ContainsFold predicate on the "payment_qrcode" field.
func PaymentQrcodeContainsFold(v string) predicate.SubscriptionOrder {
	return predicate.SubscriptionOrder(sql.FieldContainsFold(FieldPaymentQrcode, v))
}

// PaymentOpenOrderIDEQ applies the EQ predicate on the "payment_open_order_id" field.
func PaymentOpenOrderIDEQ(v string) predicate.SubscriptionOrder {
	return predicate.SubscriptionOrder(sql.FieldEQ(FieldPaymentOpenOrderID, v))
}

// PaymentOpenOrderIDNEQ applies the NEQ predicate on the "payment_open_order_id" field.
func PaymentOpenOrderIDNEQ(v string) predicate.SubscriptionOrder {
	return predicate.SubscriptionOrder(sql.FieldNEQ(FieldPaymentOpenOrderID, v))
}

// PaymentOpenOrderIDIn applies the In predicate on the "payment_open_order_id" field.
func PaymentOpenOrderIDIn(vs ...string) predicate.SubscriptionOrder {
	return predicate.SubscriptionOrder(sql.FieldIn(FieldPaymentOpenOrderID, vs...))
}

// PaymentOpenOrderIDNotIn applies the NotIn predicate on the "payment_open_order_id" field.
func PaymentOpenOrderIDNotIn(vs ...string) predicate.SubscriptionOrder {
	return predicate.SubscriptionOrder(sql.FieldNotIn(FieldPaymentOpenOrderID, vs...))
}

// PaymentOpenOrderIDGT applies the GT predicate on the "payment_open_order_id" field.
func PaymentOpenOrderIDGT(v string) predicate.SubscriptionOrder {
	return predicate.SubscriptionOrder(sql.FieldGT(FieldPaymentOpenOrderID, v))
}

// PaymentOpenOrderIDGTE applies the GTE predicate on the "payment_open_order_id" field.
func PaymentOpenOrderIDGTE(v string) predicate.SubscriptionOrder {
	return predicate.SubscriptionOrder(sql.FieldGTE(FieldPaymentOpenOrderID, v))
}

// PaymentOpenOrderIDLT applies the LT predicate on the "payment_open_order_id" field.
func PaymentOpenOrderIDLT(v string) predicate.SubscriptionOrder {
	return predicate.SubscriptionOrder(sql.FieldLT(FieldPaymentOpenOrderID, v))
}

// PaymentOpenOrderIDLTE applies the LTE predicate on the "payment_open_order_id" field.
func PaymentOpenOrderIDLTE(v string) predicate.SubscriptionOrder {
	return predicate.SubscriptionOrder(sql.FieldLTE(FieldPaymentOpenOrderID, v))
}

// PaymentOpenOrderIDContains applies the Contains predicate on the "payment_open_order_id" field.
func PaymentOpenOrderIDContains(v string) predicate.SubscriptionOrder {
	return predicate.SubscriptionOrder(sql.FieldContains(FieldPaymentOpenOrderID, v))
}

// PaymentOpenOrderIDHasPrefix applies the HasPrefix predicate on the "payment_open_order_id" field.
func PaymentOpenOrderIDHasPrefix(v string) predicate.SubscriptionOrder {
	return predicate.SubscriptionOrder(sql.FieldHasPrefix(FieldPaymentOpenOrderID, v))
}

// PaymentOpenOrderIDHasSuffix applies the HasSuffix predicate on the "payment_open_order_id" field.
func PaymentOpenOrderIDHasSuffix(v string) predicate.SubscriptionOrder {
	return predicate.SubscriptionOrder(sql.FieldHasSuffix(FieldPaymentOpenOrderID, v))
}

// PaymentOpenOrderIDIsNil applies the IsNil predicate on the "payment_open_order_id" field.
func PaymentOpenOrderIDIsNil() predicate.SubscriptionOrder {
	return predicate.SubscriptionOrder(sql.FieldIsNull(FieldPaymentOpenOrderID))
}

// PaymentOpenOrderIDNotNil applies the NotNil predicate on the "payment_open_order_id" field.
func PaymentOpenOrderIDNotNil() predicate.SubscriptionOrder {
	return predicate.SubscriptionOrder(sql.FieldNotNull(FieldPaymentOpenOrderID))
}

// PaymentOpenOrderIDEqualFold applies the EqualFold predicate on the "payment_open_order_id" field.
func PaymentOpenOrderIDEqualFold(v string) predicate.SubscriptionOrder {
	return predicate.SubscriptionOrder(sql.FieldEqualFold(FieldPaymentOpenOrderID, v))
}

// PaymentOpenOrderIDContainsFold applies the ContainsFold predicate on the "payment_open_order_id" field.
func PaymentOpenOrderIDContainsFold(v string) predicate.SubscriptionOrder {
	return predicate.SubscriptionOrder(sql.FieldContainsFold(FieldPaymentOpenOrderID, v))
}

// PaymentTransactionIDEQ applies the EQ predicate on the "payment_transaction_id" field.
func PaymentTransactionIDEQ(v string) predicate.SubscriptionOrder {
	return predicate.SubscriptionOrder(sql.FieldEQ(FieldPaymentTransactionID, v))
}

// PaymentTransactionIDNEQ applies the NEQ predicate on the "payment_transaction_id" field.
func PaymentTransactionIDNEQ(v string) predicate.SubscriptionOrder {
	return predicate.SubscriptionOrder(sql.FieldNEQ(FieldPaymentTransactionID, v))
}

// PaymentTransactionIDIn applies the In predicate on the "payment_transaction_id" field.
func PaymentTransactionIDIn(vs ...string) predicate.SubscriptionOrder {
	return predicate.SubscriptionOrder(sql.FieldIn(FieldPaymentTransactionID, vs...))
}

// PaymentTransactionIDNotIn applies the NotIn predicate on the "payment_transaction_id" field.
func PaymentTransactionIDNotIn(vs ...string) predicate.SubscriptionOrder {
	return predicate.SubscriptionOrder(sql.FieldNotIn(FieldPaymentTransactionID, vs...))
}

// PaymentTransactionIDGT applies the GT predicate on the "payment_transaction_id" field.
func PaymentTransactionIDGT(v string) predicate.SubscriptionOrder {
	return predicate.SubscriptionOrder(sql.FieldGT(FieldPaymentTransactionID, v))
}

// PaymentTransactionIDGTE applies the GTE predicate on the "payment_transaction_id" field.
func PaymentTransactionIDGTE(v string) predicate.SubscriptionOrder {
	return predicate.SubscriptionOrder(sql.FieldGTE(FieldPaymentTransactionID, v))
}

// PaymentTransactionIDLT applies the LT predicate on the "payment_transaction_id" field.
func PaymentTransactionIDLT(v string) predicate.SubscriptionOrder {
	return predicate.SubscriptionOrder(sql.FieldLT(FieldPaymentTransactionID, v))
}

// PaymentTransactionIDLTE applies the LTE predicate on the "payment_transaction_id" field.
func PaymentTransactionIDLTE(v string) predicate.SubscriptionOrder {
	return predicate.SubscriptionOrder(sql.FieldLTE(FieldPaymentTransactionID, v))
}

// PaymentTransactionIDContains applies the Contains predicate on the "payment_transaction_id" field.
func PaymentTransactionIDContains(v string) predicate.SubscriptionOrder {
	return predicate.SubscriptionOrder(sql.FieldContains(FieldPaymentTransactionID, v))
}

// PaymentTransactionIDHasPrefix applies the HasPrefix predicate on the "payment_transaction_id" field.
func PaymentTransactionIDHasPrefix(v string) predicate.SubscriptionOrder {
	return predicate.SubscriptionOrder(sql.FieldHasPrefix(FieldPaymentTransactionID, v))
}

// PaymentTransactionIDHasSuffix applies the HasSuffix predicate on the "payment_transaction_id" field.
func PaymentTransactionIDHasSuffix(v string) predicate.SubscriptionOrder {
	return predicate.SubscriptionOrder(sql.FieldHasSuffix(FieldPaymentTransactionID, v))
}

// PaymentTransactionIDIsNil applies the IsNil predicate on the "payment_transaction_id" field.
func PaymentTransactionIDIsNil() predicate.SubscriptionOrder {
	return predicate.SubscriptionOrder(sql.FieldIsNull(FieldPaymentTransactionID))
}

// PaymentTransactionIDNotNil applies the NotNil predicate on the "payment_transaction_id" field.
func PaymentTransactionIDNotNil() predicate.SubscriptionOrder {
	return predicate.SubscriptionOrder(sql.FieldNotNull(FieldPaymentTransactionID))
}

// PaymentTransactionIDEqualFold applies the EqualFold predicate on the "payment_transaction_id" field.
func PaymentTransactionIDEqualFold(v string) predicate.SubscriptionOrder {
	return predicate.SubscriptionOrder(sql.FieldEqualFold(FieldPaymentTransactionID, v))
}

// PaymentTransactionIDContainsFold applies the ContainsFold predicate on the "payment_transaction_id" field.
func PaymentTransactionIDContainsFold(v string) predicate.SubscriptionOrder {
	return predicate.SubscriptionOrder(sql.FieldContainsFold(FieldPaymentTransactionID, v))
}

// PaymentPluginEQ applies the EQ predicate on the "payment_plugin" field.
func PaymentPluginEQ(v string) predicate.SubscriptionOrder {
	return predicate.SubscriptionOrder(sql.FieldEQ(FieldPaymentPlugin, v))
}

// PaymentPluginNEQ applies the NEQ predicate on the "payment_plugin" field.
func PaymentPluginNEQ(v string) predicate.SubscriptionOrder {
	return predicate.SubscriptionOrder(sql.FieldNEQ(FieldPaymentPlugin, v))
}

// PaymentPluginIn applies the In predicate on the "payment_plugin" field.
func PaymentPluginIn(vs ...string) predicate.SubscriptionOrder {
	return predicate.SubscriptionOrder(sql.FieldIn(FieldPaymentPlugin, vs...))
}

// PaymentPluginNotIn applies the NotIn predicate on the "payment_plugin" field.
func PaymentPluginNotIn(vs ...string) predicate.SubscriptionOrder {
	return predicate.SubscriptionOrder(sql.FieldNotIn(FieldPaymentPlugin, vs...))
}

// PaymentPluginGT applies the GT predicate on the "payment_plugin" field.
func PaymentPluginGT(v string) predicate.SubscriptionOrder {
	return predicate.SubscriptionOrder(sql.FieldGT(FieldPaymentPlugin, v))
}

// PaymentPluginGTE applies the GTE predicate on the "payment_plugin" field.
func PaymentPluginGTE(v string) predicate.SubscriptionOrder {
	return predicate.SubscriptionOrder(sql.FieldGTE(FieldPaymentPlugin, v))
}

// PaymentPluginLT applies the LT predicate on the "payment_plugin" field.
func PaymentPluginLT(v string) predicate.SubscriptionOrder {
	return predicate.SubscriptionOrder(sql.FieldLT(FieldPaymentPlugin, v))
}

// PaymentPluginLTE applies the LTE predicate on the "payment_plugin" field.
func PaymentPluginLTE(v string) predicate.SubscriptionOrder {
	return predicate.SubscriptionOrder(sql.FieldLTE(FieldPaymentPlugin, v))
}

// PaymentPluginContains applies the Contains predicate on the "payment_plugin" field.
func PaymentPluginContains(v string) predicate.SubscriptionOrder {
	return predicate.SubscriptionOrder(sql.FieldContains(FieldPaymentPlugin, v))
}

// PaymentPluginHasPrefix applies the HasPrefix predicate on the "payment_plugin" field.
func PaymentPluginHasPrefix(v string) predicate.SubscriptionOrder {
	return predicate.SubscriptionOrder(sql.FieldHasPrefix(FieldPaymentPlugin, v))
}

// PaymentPluginHasSuffix applies the HasSuffix predicate on the "payment_plugin" field.
func PaymentPluginHasSuffix(v string) predicate.SubscriptionOrder {
	return predicate.SubscriptionOrder(sql.FieldHasSuffix(FieldPaymentPlugin, v))
}

// PaymentPluginIsNil applies the IsNil predicate on the "payment_plugin" field.
func PaymentPluginIsNil() predicate.SubscriptionOrder {
	return predicate.SubscriptionOrder(sql.FieldIsNull(FieldPaymentPlugin))
}

// PaymentPluginNotNil applies the NotNil predicate on the "payment_plugin" field.
func PaymentPluginNotNil() predicate.SubscriptionOrder {
	return predicate.SubscriptionOrder(sql.FieldNotNull(FieldPaymentPlugin))
}

// PaymentPluginEqualFold applies the EqualFold predicate on the "payment_plugin" field.
func PaymentPluginEqualFold(v string) predicate.SubscriptionOrder {
	return predicate.SubscriptionOrder(sql.FieldEqualFold(FieldPaymentPlugin, v))
}

// PaymentPluginContainsFold applies the ContainsFold predicate on the "payment_plugin" field.
func PaymentPluginContainsFold(v string) predicate.SubscriptionOrder {
	return predicate.SubscriptionOrder(sql.FieldContainsFold(FieldPaymentPlugin, v))
}

// StatusEQ applies the EQ predicate on the "status" field.
func StatusEQ(v string) predicate.SubscriptionOrder {
	return predicate.SubscriptionOrder(sql.FieldEQ(FieldStatus, v))
}

// StatusNEQ applies the NEQ predicate on the "status" field.
func StatusNEQ(v string) predicate.SubscriptionOrder {
	return predicate.SubscriptionOrder(sql.FieldNEQ(FieldStatus, v))
}

// StatusIn applies the In predicate on the "status" field.
func StatusIn(vs ...string) predicate.SubscriptionOrder {
	return predicate.SubscriptionOrder(sql.FieldIn(FieldStatus, vs...))
}

// StatusNotIn applies the NotIn predicate on the "status" field.
func StatusNotIn(vs ...string) predicate.SubscriptionOrder {
	return predicate.SubscriptionOrder(sql.FieldNotIn(FieldStatus, vs...))
}

// StatusGT applies the GT predicate on the "status" field.
func StatusGT(v string) predicate.SubscriptionOrder {
	return predicate.SubscriptionOrder(sql.FieldGT(FieldStatus, v))
}

// StatusGTE applies the GTE predicate on the "status" field.
func StatusGTE(v string) predicate.SubscriptionOrder {
	return predicate.SubscriptionOrder(sql.FieldGTE(FieldStatus, v))
}

// StatusLT applies the LT predicate on the "status" field.
func StatusLT(v string) predicate.SubscriptionOrder {
	return predicate.SubscriptionOrder(sql.FieldLT(FieldStatus, v))
}

// StatusLTE applies the LTE predicate on the "status" field.
func StatusLTE(v string) predicate.SubscriptionOrder {
	return predicate.SubscriptionOrder(sql.FieldLTE(FieldStatus, v))
}

// StatusContains applies the Contains predicate on the "status" field.
func StatusContains(v string) predicate.SubscriptionOrder {
	return predicate.SubscriptionOrder(sql.FieldContains(FieldStatus, v))
}

// StatusHasPrefix applies the HasPrefix predicate on the "status" field.
func StatusHasPrefix(v string) predicate.SubscriptionOrder {
	return predicate.SubscriptionOrder(sql.FieldHasPrefix(FieldStatus, v))
}

// StatusHasSuffix applies the HasSuffix predicate on the "status" field.
func StatusHasSuffix(v string) predicate.SubscriptionOrder {
	return predicate.SubscriptionOrder(sql.FieldHasSuffix(FieldStatus, v))
}

// StatusEqualFold applies the EqualFold predicate on the "status" field.
func StatusEqualFold(v string) predicate.SubscriptionOrder {
	return predicate.SubscriptionOrder(sql.FieldEqualFold(FieldStatus, v))
}

// StatusContainsFold applies the ContainsFold predicate on the "status" field.
func StatusContainsFold(v string) predicate.SubscriptionOrder {
	return predicate.SubscriptionOrder(sql.FieldContainsFold(FieldStatus, v))
}

// AmountEQ applies the EQ predicate on the "amount" field.
func AmountEQ(v float64) predicate.SubscriptionOrder {
	return predicate.SubscriptionOrder(sql.FieldEQ(FieldAmount, v))
}

// AmountNEQ applies the NEQ predicate on the "amount" field.
func AmountNEQ(v float64) predicate.SubscriptionOrder {
	return predicate.SubscriptionOrder(sql.FieldNEQ(FieldAmount, v))
}

// AmountIn applies the In predicate on the "amount" field.
func AmountIn(vs ...float64) predicate.SubscriptionOrder {
	return predicate.SubscriptionOrder(sql.FieldIn(FieldAmount, vs...))
}

// AmountNotIn applies the NotIn predicate on the "amount" field.
func AmountNotIn(vs ...float64) predicate.SubscriptionOrder {
	return predicate.SubscriptionOrder(sql.FieldNotIn(FieldAmount, vs...))
}

// AmountGT applies the GT predicate on the "amount" field.
func AmountGT(v float64) predicate.SubscriptionOrder {
	return predicate.SubscriptionOrder(sql.FieldGT(FieldAmount, v))
}

// AmountGTE applies the GTE predicate on the "amount" field.
func AmountGTE(v float64) predicate.SubscriptionOrder {
	return predicate.SubscriptionOrder(sql.FieldGTE(FieldAmount, v))
}

// AmountLT applies the LT predicate on the "amount" field.
func AmountLT(v float64) predicate.SubscriptionOrder {
	return predicate.SubscriptionOrder(sql.FieldLT(FieldAmount, v))
}

// AmountLTE applies the LTE predicate on the "amount" field.
func AmountLTE(v float64) predicate.SubscriptionOrder {
	return predicate.SubscriptionOrder(sql.FieldLTE(FieldAmount, v))
}

// CurrencyEQ applies the EQ predicate on the "currency" field.
func CurrencyEQ(v string) predicate.SubscriptionOrder {
	return predicate.SubscriptionOrder(sql.FieldEQ(FieldCurrency, v))
}

// CurrencyNEQ applies the NEQ predicate on the "currency" field.
func CurrencyNEQ(v string) predicate.SubscriptionOrder {
	return predicate.SubscriptionOrder(sql.FieldNEQ(FieldCurrency, v))
}

// CurrencyIn applies the In predicate on the "currency" field.
func CurrencyIn(vs ...string) predicate.SubscriptionOrder {
	return predicate.SubscriptionOrder(sql.FieldIn(FieldCurrency, vs...))
}

// CurrencyNotIn applies the NotIn predicate on the "currency" field.
func CurrencyNotIn(vs ...string) predicate.SubscriptionOrder {
	return predicate.SubscriptionOrder(sql.FieldNotIn(FieldCurrency, vs...))
}

// CurrencyGT applies the GT predicate on the "currency" field.
func CurrencyGT(v string) predicate.SubscriptionOrder {
	return predicate.SubscriptionOrder(sql.FieldGT(FieldCurrency, v))
}

// CurrencyGTE applies the GTE predicate on the "currency" field.
func CurrencyGTE(v string) predicate.SubscriptionOrder {
	return predicate.SubscriptionOrder(sql.FieldGTE(FieldCurrency, v))
}

// CurrencyLT applies the LT predicate on the "currency" field.
func CurrencyLT(v string) predicate.SubscriptionOrder {
	return predicate.SubscriptionOrder(sql.FieldLT(FieldCurrency, v))
}

// CurrencyLTE applies the LTE predicate on the "currency" field.
func CurrencyLTE(v string) predicate.SubscriptionOrder {
	return predicate.SubscriptionOrder(sql.FieldLTE(FieldCurrency, v))
}

// CurrencyContains applies the Contains predicate on the "currency" field.
func CurrencyContains(v string) predicate.SubscriptionOrder {
	return predicate.SubscriptionOrder(sql.FieldContains(FieldCurrency, v))
}

// CurrencyHasPrefix applies the HasPrefix predicate on the "currency" field.
func CurrencyHasPrefix(v string) predicate.SubscriptionOrder {
	return predicate.SubscriptionOrder(sql.FieldHasPrefix(FieldCurrency, v))
}

// CurrencyHasSuffix applies the HasSuffix predicate on the "currency" field.
func CurrencyHasSuffix(v string) predicate.SubscriptionOrder {
	return predicate.SubscriptionOrder(sql.FieldHasSuffix(FieldCurrency, v))
}

// CurrencyEqualFold applies the EqualFold predicate on the "currency" field.
func CurrencyEqualFold(v string) predicate.SubscriptionOrder {
	return predicate.SubscriptionOrder(sql.FieldEqualFold(FieldCurrency, v))
}

// CurrencyContainsFold applies the ContainsFold predicate on the "currency" field.
func CurrencyContainsFold(v string) predicate.SubscriptionOrder {
	return predicate.SubscriptionOrder(sql.FieldContainsFold(FieldCurrency, v))
}

// ValidityDaysEQ applies the EQ predicate on the "validity_days" field.
func ValidityDaysEQ(v int) predicate.SubscriptionOrder {
	return predicate.SubscriptionOrder(sql.FieldEQ(FieldValidityDays, v))
}

// ValidityDaysNEQ applies the NEQ predicate on the "validity_days" field.
func ValidityDaysNEQ(v int) predicate.SubscriptionOrder {
	return predicate.SubscriptionOrder(sql.FieldNEQ(FieldValidityDays, v))
}

// ValidityDaysIn applies the In predicate on the "validity_days" field.
func ValidityDaysIn(vs ...int) predicate.SubscriptionOrder {
	return predicate.SubscriptionOrder(sql.FieldIn(FieldValidityDays, vs...))
}

// ValidityDaysNotIn applies the NotIn predicate on the "validity_days" field.
func ValidityDaysNotIn(vs ...int) predicate.SubscriptionOrder {
	return predicate.SubscriptionOrder(sql.FieldNotIn(FieldValidityDays, vs...))
}

// ValidityDaysGT applies the GT predicate on the "validity_days" field.
func ValidityDaysGT(v int) predicate.SubscriptionOrder {
	return predicate.SubscriptionOrder(sql.FieldGT(FieldValidityDays, v))
}

// ValidityDaysGTE applies the GTE predicate on the "validity_days" field.
func ValidityDaysGTE(v int) predicate.SubscriptionOrder {
	return predicate.SubscriptionOrder(sql.FieldGTE(FieldValidityDays, v))
}

// ValidityDaysLT applies the LT predicate on the "validity_days" field.
func ValidityDaysLT(v int) predicate.SubscriptionOrder {
	return predicate.SubscriptionOrder(sql.FieldLT(FieldValidityDays, v))
}

// ValidityDaysLTE applies the LTE predicate on the "validity_days" field.
func ValidityDaysLTE(v int) predicate.SubscriptionOrder {
	return predicate.SubscriptionOrder(sql.FieldLTE(FieldValidityDays, v))
}

// PaidAtEQ applies the EQ predicate on the "paid_at" field.
func PaidAtEQ(v time.Time) predicate.SubscriptionOrder {
	return predicate.SubscriptionOrder(sql.FieldEQ(FieldPaidAt, v))
}

// PaidAtNEQ applies the NEQ predicate on the "paid_at" field.
func PaidAtNEQ(v time.Time) predicate.SubscriptionOrder {
	return predicate.SubscriptionOrder(sql.FieldNEQ(FieldPaidAt, v))
}

// PaidAtIn applies the In predicate on the "paid_at" field.
func PaidAtIn(vs ...time.Time) predicate.SubscriptionOrder {
	return predicate.SubscriptionOrder(sql.FieldIn(FieldPaidAt, vs...))
}

// PaidAtNotIn applies the NotIn predicate on the "paid_at" field.
func PaidAtNotIn(vs ...time.Time) predicate.SubscriptionOrder {
	return predicate.SubscriptionOrder(sql.FieldNotIn(FieldPaidAt, vs...))
}

// PaidAtGT applies the GT predicate on the "paid_at" field.
func PaidAtGT(v time.Time) predicate.SubscriptionOrder {
	return predicate.SubscriptionOrder(sql.FieldGT(FieldPaidAt, v))
}

// PaidAtGTE applies the GTE predicate on the "paid_at" field.
func PaidAtGTE(v time.Time) predicate.SubscriptionOrder {
	return predicate.SubscriptionOrder(sql.FieldGTE(FieldPaidAt, v))
}

// PaidAtLT applies the LT predicate on the "paid_at" field.
func PaidAtLT(v time.Time) predicate.SubscriptionOrder {
	return predicate.SubscriptionOrder(sql.FieldLT(FieldPaidAt, v))
}

// PaidAtLTE applies the LTE predicate on the "paid_at" field.
func PaidAtLTE(v time.Time) predicate.SubscriptionOrder {
	return predicate.SubscriptionOrder(sql.FieldLTE(FieldPaidAt, v))
}

// PaidAtIsNil applies the IsNil predicate on the "paid_at" field.
func PaidAtIsNil() predicate.SubscriptionOrder {
	return predicate.SubscriptionOrder(sql.FieldIsNull(FieldPaidAt))
}

// PaidAtNotNil applies the NotNil predicate on the "paid_at" field.
func PaidAtNotNil() predicate.SubscriptionOrder {
	return predicate.SubscriptionOrder(sql.FieldNotNull(FieldPaidAt))
}

// CanceledAtEQ applies the EQ predicate on the "canceled_at" field.
func CanceledAtEQ(v time.Time) predicate.SubscriptionOrder {
	return predicate.SubscriptionOrder(sql.FieldEQ(FieldCanceledAt, v))
}

// CanceledAtNEQ applies the NEQ predicate on the "canceled_at" field.
func CanceledAtNEQ(v time.Time) predicate.SubscriptionOrder {
	return predicate.SubscriptionOrder(sql.FieldNEQ(FieldCanceledAt, v))
}

// CanceledAtIn applies the In predicate on the "canceled_at" field.
func CanceledAtIn(vs ...time.Time) predicate.SubscriptionOrder {
	return predicate.SubscriptionOrder(sql.FieldIn(FieldCanceledAt, vs...))
}

// CanceledAtNotIn applies the NotIn predicate on the "canceled_at" field.
func CanceledAtNotIn(vs ...time.Time) predicate.SubscriptionOrder {
	return predicate.SubscriptionOrder(sql.FieldNotIn(FieldCanceledAt, vs...))
}

// CanceledAtGT applies the GT predicate on the "canceled_at" field.
func CanceledAtGT(v time.Time) predicate.SubscriptionOrder {
	return predicate.SubscriptionOrder(sql.FieldGT(FieldCanceledAt, v))
}

// CanceledAtGTE applies the GTE predicate on the "canceled_at" field.
func CanceledAtGTE(v time.Time) predicate.SubscriptionOrder {
	return predicate.SubscriptionOrder(sql.FieldGTE(FieldCanceledAt, v))
}

// CanceledAtLT applies the LT predicate on the "canceled_at" field.
func CanceledAtLT(v time.Time) predicate.SubscriptionOrder {
	return predicate.SubscriptionOrder(sql.FieldLT(FieldCanceledAt, v))
}

// CanceledAtLTE applies the LTE predicate on the "canceled_at" field.
func CanceledAtLTE(v time.Time) predicate.SubscriptionOrder {
	return predicate.SubscriptionOrder(sql.FieldLTE(FieldCanceledAt, v))
}

// CanceledAtIsNil applies the IsNil predicate on the "canceled_at" field.
func CanceledAtIsNil() predicate.SubscriptionOrder {
	return predicate.SubscriptionOrder(sql.FieldIsNull(FieldCanceledAt))
}

// CanceledAtNotNil applies the NotNil predicate on the "canceled_at" field.
func CanceledAtNotNil() predicate.SubscriptionOrder {
	return predicate.SubscriptionOrder(sql.FieldNotNull(FieldCanceledAt))
}

// NotesEQ applies the EQ predicate on the "notes" field.
func NotesEQ(v string) predicate.SubscriptionOrder {
	return predicate.SubscriptionOrder(sql.FieldEQ(FieldNotes, v))
}

// NotesNEQ applies the NEQ predicate on the "notes" field.
func NotesNEQ(v string) predicate.SubscriptionOrder {
	return predicate.SubscriptionOrder(sql.FieldNEQ(FieldNotes, v))
}

// NotesIn applies the In predicate on the "notes" field.
func NotesIn(vs ...string) predicate.SubscriptionOrder {
	return predicate.SubscriptionOrder(sql.FieldIn(FieldNotes, vs...))
}

// NotesNotIn applies the NotIn predicate on the "notes" field.
func NotesNotIn(vs ...string) predicate.SubscriptionOrder {
	return predicate.SubscriptionOrder(sql.FieldNotIn(FieldNotes, vs...))
}

// NotesGT applies the GT predicate on the "notes" field.
func NotesGT(v string) predicate.SubscriptionOrder {
	return predicate.SubscriptionOrder(sql.FieldGT(FieldNotes, v))
}

// NotesGTE applies the GTE predicate on the "notes" field.
func NotesGTE(v string) predicate.SubscriptionOrder {
	return predicate.SubscriptionOrder(sql.FieldGTE(FieldNotes, v))
}

// NotesLT applies the LT predicate on the "notes" field.
func NotesLT(v string) predicate.SubscriptionOrder {
	return predicate.SubscriptionOrder(sql.FieldLT(FieldNotes, v))
}

// NotesLTE applies the LTE predicate on the "notes" field.
func NotesLTE(v string) predicate.SubscriptionOrder {
	return predicate.SubscriptionOrder(sql.FieldLTE(FieldNotes, v))
}

// NotesContains applies the Contains predicate on the "notes" field.
func NotesContains(v string) predicate.SubscriptionOrder {
	return predicate.SubscriptionOrder(sql.FieldContains(FieldNotes, v))
}

// NotesHasPrefix applies the HasPrefix predicate on the "notes" field.
func NotesHasPrefix(v string) predicate.SubscriptionOrder {
	return predicate.SubscriptionOrder(sql.FieldHasPrefix(FieldNotes, v))
}

// NotesHasSuffix applies the HasSuffix predicate on the "notes" field.
func NotesHasSuffix(v string) predicate.SubscriptionOrder {
	return predicate.SubscriptionOrder(sql.FieldHasSuffix(FieldNotes, v))
}

// NotesIsNil applies the IsNil predicate on the "notes" field.
func NotesIsNil() predicate.SubscriptionOrder {
	return predicate.SubscriptionOrder(sql.FieldIsNull(FieldNotes))
}

// NotesNotNil applies the NotNil predicate on the "notes" field.
func NotesNotNil() predicate.SubscriptionOrder {
	return predicate.SubscriptionOrder(sql.FieldNotNull(FieldNotes))
}

// NotesEqualFold applies the EqualFold predicate on the "notes" field.
func NotesEqualFold(v string) predicate.SubscriptionOrder {
	return predicate.SubscriptionOrder(sql.FieldEqualFold(FieldNotes, v))
}

// NotesContainsFold applies the ContainsFold predicate on the "notes" field.
func NotesContainsFold(v string) predicate.SubscriptionOrder {
	return predicate.SubscriptionOrder(sql.FieldContainsFold(FieldNotes, v))
}

// HasUser applies the HasEdge predicate on the "user" edge.
func HasUser() predicate.SubscriptionOrder {
	return predicate.SubscriptionOrder(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, UserTable, UserColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasUserWith applies the HasEdge predicate on the "user" edge with a given conditions (other predicates).
func HasUserWith(preds ...predicate.User) predicate.SubscriptionOrder {
	return predicate.SubscriptionOrder(func(s *sql.Selector) {
		step := newUserStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// HasGroup applies the HasEdge predicate on the "group" edge.
func HasGroup() predicate.SubscriptionOrder {
	return predicate.SubscriptionOrder(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, GroupTable, GroupColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasGroupWith applies the HasEdge predicate on the "group" edge with a given conditions (other predicates).
func HasGroupWith(preds ...predicate.Group) predicate.SubscriptionOrder {
	return predicate.SubscriptionOrder(func(s *sql.Selector) {
		step := newGroupStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// HasSubscription applies the HasEdge predicate on the "subscription" edge.
func HasSubscription() predicate.SubscriptionOrder {
	return predicate.SubscriptionOrder(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, SubscriptionTable, SubscriptionColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasSubscriptionWith applies the HasEdge predicate on the "subscription" edge with a given conditions (other predicates).
func HasSubscriptionWith(preds ...predicate.UserSubscription) predicate.SubscriptionOrder {
	return predicate.SubscriptionOrder(func(s *sql.Selector) {
		step := newSubscriptionStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.SubscriptionOrder) predicate.SubscriptionOrder {
	return predicate.SubscriptionOrder(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.SubscriptionOrder) predicate.SubscriptionOrder {
	return predicate.SubscriptionOrder(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.SubscriptionOrder) predicate.SubscriptionOrder {
	return predicate.SubscriptionOrder(sql.NotPredicates(p))
}
