// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/Wei-Shaw/sub2api/ent/group"
	"github.com/Wei-Shaw/sub2api/ent/predicate"
	"github.com/Wei-Shaw/sub2api/ent/subscriptionorder"
	"github.com/Wei-Shaw/sub2api/ent/user"
	"github.com/Wei-Shaw/sub2api/ent/usersubscription"
)

// SubscriptionOrderUpdate is the builder for updating SubscriptionOrder entities.
type SubscriptionOrderUpdate struct {
	config
	hooks    []Hook
	mutation *SubscriptionOrderMutation
}

// Where appends a list predicates to the SubscriptionOrderUpdate builder.
func (_u *SubscriptionOrderUpdate) Where(ps ...predicate.SubscriptionOrder) *SubscriptionOrderUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *SubscriptionOrderUpdate) SetUpdatedAt(v time.Time) *SubscriptionOrderUpdate {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetOrderNo sets the "order_no" field.
func (_u *SubscriptionOrderUpdate) SetOrderNo(v string) *SubscriptionOrderUpdate {
	_u.mutation.SetOrderNo(v)
	return _u
}

// SetNillableOrderNo sets the "order_no" field if the given value is not nil.
func (_u *SubscriptionOrderUpdate) SetNillableOrderNo(v *string) *SubscriptionOrderUpdate {
	if v != nil {
		_u.SetOrderNo(*v)
	}
	return _u
}

// SetUserID sets the "user_id" field.
func (_u *SubscriptionOrderUpdate) SetUserID(v int64) *SubscriptionOrderUpdate {
	_u.mutation.SetUserID(v)
	return _u
}

// SetNillableUserID sets the "user_id" field if the given value is not nil.
func (_u *SubscriptionOrderUpdate) SetNillableUserID(v *int64) *SubscriptionOrderUpdate {
	if v != nil {
		_u.SetUserID(*v)
	}
	return _u
}

// SetGroupID sets the "group_id" field.
func (_u *SubscriptionOrderUpdate) SetGroupID(v int64) *SubscriptionOrderUpdate {
	_u.mutation.SetGroupID(v)
	return _u
}

// SetNillableGroupID sets the "group_id" field if the given value is not nil.
func (_u *SubscriptionOrderUpdate) SetNillableGroupID(v *int64) *SubscriptionOrderUpdate {
	if v != nil {
		_u.SetGroupID(*v)
	}
	return _u
}

// SetSubscriptionID sets the "subscription_id" field.
func (_u *SubscriptionOrderUpdate) SetSubscriptionID(v int64) *SubscriptionOrderUpdate {
	_u.mutation.SetSubscriptionID(v)
	return _u
}

// SetNillableSubscriptionID sets the "subscription_id" field if the given value is not nil.
func (_u *SubscriptionOrderUpdate) SetNillableSubscriptionID(v *int64) *SubscriptionOrderUpdate {
	if v != nil {
		_u.SetSubscriptionID(*v)
	}
	return _u
}

// ClearSubscriptionID clears the value of the "subscription_id" field.
func (_u *SubscriptionOrderUpdate) ClearSubscriptionID() *SubscriptionOrderUpdate {
	_u.mutation.ClearSubscriptionID()
	return _u
}

// SetPaymentProvider sets the "payment_provider" field.
func (_u *SubscriptionOrderUpdate) SetPaymentProvider(v string) *SubscriptionOrderUpdate {
	_u.mutation.SetPaymentProvider(v)
	return _u
}

// SetNillablePaymentProvider sets the "payment_provider" field if the given value is not nil.
func (_u *SubscriptionOrderUpdate) SetNillablePaymentProvider(v *string) *SubscriptionOrderUpdate {
	if v != nil {
		_u.SetPaymentProvider(*v)
	}
	return _u
}

// SetPaymentURL sets the "payment_url" field.
func (_u *SubscriptionOrderUpdate) SetPaymentURL(v string) *SubscriptionOrderUpdate {
	_u.mutation.SetPaymentURL(v)
	return _u
}

// SetNillablePaymentURL sets the "payment_url" field if the given value is not nil.
func (_u *SubscriptionOrderUpdate) SetNillablePaymentURL(v *string) *SubscriptionOrderUpdate {
	if v != nil {
		_u.SetPaymentURL(*v)
	}
	return _u
}

// ClearPaymentURL clears the value of the "payment_url" field.
func (_u *SubscriptionOrderUpdate) ClearPaymentURL() *SubscriptionOrderUpdate {
	_u.mutation.ClearPaymentURL()
	return _u
}

// SetPaymentQrcode sets the "payment_qrcode" field.
func (_u *SubscriptionOrderUpdate) SetPaymentQrcode(v string) *SubscriptionOrderUpdate {
	_u.mutation.SetPaymentQrcode(v)
	return _u
}

// SetNillablePaymentQrcode sets the "payment_qrcode" field if the given value is not nil.
func (_u *SubscriptionOrderUpdate) SetNillablePaymentQrcode(v *string) *SubscriptionOrderUpdate {
	if v != nil {
		_u.SetPaymentQrcode(*v)
	}
	return _u
}

// ClearPaymentQrcode clears the value of the "payment_qrcode" field.
func (_u *SubscriptionOrderUpdate) ClearPaymentQrcode() *SubscriptionOrderUpdate {
	_u.mutation.ClearPaymentQrcode()
	return _u
}

// SetPaymentOpenOrderID sets the "payment_open_order_id" field.
func (_u *SubscriptionOrderUpdate) SetPaymentOpenOrderID(v string) *SubscriptionOrderUpdate {
	_u.mutation.SetPaymentOpenOrderID(v)
	return _u
}

// SetNillablePaymentOpenOrderID sets the "payment_open_order_id" field if the given value is not nil.
func (_u *SubscriptionOrderUpdate) SetNillablePaymentOpenOrderID(v *string) *SubscriptionOrderUpdate {
	if v != nil {
		_u.SetPaymentOpenOrderID(*v)
	}
	return _u
}

// ClearPaymentOpenOrderID clears the value of the "payment_open_order_id" field.
func (_u *SubscriptionOrderUpdate) ClearPaymentOpenOrderID() *SubscriptionOrderUpdate {
	_u.mutation.ClearPaymentOpenOrderID()
	return _u
}

// SetPaymentTransactionID sets the "payment_transaction_id" field.
func (_u *SubscriptionOrderUpdate) SetPaymentTransactionID(v string) *SubscriptionOrderUpdate {
	_u.mutation.SetPaymentTransactionID(v)
	return _u
}

// SetNillablePaymentTransactionID sets the "payment_transaction_id" field if the given value is not nil.
func (_u *SubscriptionOrderUpdate) SetNillablePaymentTransactionID(v *string) *SubscriptionOrderUpdate {
	if v != nil {
		_u.SetPaymentTransactionID(*v)
	}
	return _u
}

// ClearPaymentTransactionID clears the value of the "payment_transaction_id" field.
func (_u *SubscriptionOrderUpdate) ClearPaymentTransactionID() *SubscriptionOrderUpdate {
	_u.mutation.ClearPaymentTransactionID()
	return _u
}

// SetPaymentPlugin sets the "payment_plugin" field.
func (_u *SubscriptionOrderUpdate) SetPaymentPlugin(v string) *SubscriptionOrderUpdate {
	_u.mutation.SetPaymentPlugin(v)
	return _u
}

// SetNillablePaymentPlugin sets the "payment_plugin" field if the given value is not nil.
func (_u *SubscriptionOrderUpdate) SetNillablePaymentPlugin(v *string) *SubscriptionOrderUpdate {
	if v != nil {
		_u.SetPaymentPlugin(*v)
	}
	return _u
}

// ClearPaymentPlugin clears the value of the "payment_plugin" field.
func (_u *SubscriptionOrderUpdate) ClearPaymentPlugin() *SubscriptionOrderUpdate {
	_u.mutation.ClearPaymentPlugin()
	return _u
}

// SetStatus sets the "status" field.
func (_u *SubscriptionOrderUpdate) SetStatus(v string) *SubscriptionOrderUpdate {
	_u.mutation.SetStatus(v)
	return _u
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_u *SubscriptionOrderUpdate) SetNillableStatus(v *string) *SubscriptionOrderUpdate {
	if v != nil {
		_u.SetStatus(*v)
	}
	return _u
}

// SetAmount sets the "amount" field.
func (_u *SubscriptionOrderUpdate) SetAmount(v float64) *SubscriptionOrderUpdate {
	_u.mutation.ResetAmount()
	_u.mutation.SetAmount(v)
	return _u
}

// SetNillableAmount sets the "amount" field if the given value is not nil.
func (_u *SubscriptionOrderUpdate) SetNillableAmount(v *float64) *SubscriptionOrderUpdate {
	if v != nil {
		_u.SetAmount(*v)
	}
	return _u
}

// AddAmount adds value to the "amount" field.
func (_u *SubscriptionOrderUpdate) AddAmount(v float64) *SubscriptionOrderUpdate {
	_u.mutation.AddAmount(v)
	return _u
}

// SetCurrency sets the "currency" field.
func (_u *SubscriptionOrderUpdate) SetCurrency(v string) *SubscriptionOrderUpdate {
	_u.mutation.SetCurrency(v)
	return _u
}

// SetNillableCurrency sets the "currency" field if the given value is not nil.
func (_u *SubscriptionOrderUpdate) SetNillableCurrency(v *string) *SubscriptionOrderUpdate {
	if v != nil {
		_u.SetCurrency(*v)
	}
	return _u
}

// SetValidityDays sets the "validity_days" field.
func (_u *SubscriptionOrderUpdate) SetValidityDays(v int) *SubscriptionOrderUpdate {
	_u.mutation.ResetValidityDays()
	_u.mutation.SetValidityDays(v)
	return _u
}

// SetNillableValidityDays sets the "validity_days" field if the given value is not nil.
func (_u *SubscriptionOrderUpdate) SetNillableValidityDays(v *int) *SubscriptionOrderUpdate {
	if v != nil {
		_u.SetValidityDays(*v)
	}
	return _u
}

// AddValidityDays adds value to the "validity_days" field.
func (_u *SubscriptionOrderUpdate) AddValidityDays(v int) *SubscriptionOrderUpdate {
	_u.mutation.AddValidityDays(v)
	return _u
}

// SetPaidAt sets the "paid_at" field.
func (_u *SubscriptionOrderUpdate) SetPaidAt(v time.Time) *SubscriptionOrderUpdate {
	_u.mutation.SetPaidAt(v)
	return _u
}

// SetNillablePaidAt sets the "paid_at" field if the given value is not nil.
func (_u *SubscriptionOrderUpdate) SetNillablePaidAt(v *time.Time) *SubscriptionOrderUpdate {
	if v != nil {
		_u.SetPaidAt(*v)
	}
	return _u
}

// ClearPaidAt clears the value of the "paid_at" field.
func (_u *SubscriptionOrderUpdate) ClearPaidAt() *SubscriptionOrderUpdate {
	_u.mutation.ClearPaidAt()
	return _u
}

// SetCanceledAt sets the "canceled_at" field.
func (_u *SubscriptionOrderUpdate) SetCanceledAt(v time.Time) *SubscriptionOrderUpdate {
	_u.mutation.SetCanceledAt(v)
	return _u
}

// SetNillableCanceledAt sets the "canceled_at" field if the given value is not nil.
func (_u *SubscriptionOrderUpdate) SetNillableCanceledAt(v *time.Time) *SubscriptionOrderUpdate {
	if v != nil {
		_u.SetCanceledAt(*v)
	}
	return _u
}

// ClearCanceledAt clears the value of the "canceled_at" field.
func (_u *SubscriptionOrderUpdate) ClearCanceledAt() *SubscriptionOrderUpdate {
	_u.mutation.ClearCanceledAt()
	return _u
}

// SetNotes sets the "notes" field.
func (_u *SubscriptionOrderUpdate) SetNotes(v string) *SubscriptionOrderUpdate {
	_u.mutation.SetNotes(v)
	return _u
}

// SetNillableNotes sets the "notes" field if the given value is not nil.
func (_u *SubscriptionOrderUpdate) SetNillableNotes(v *string) *SubscriptionOrderUpdate {
	if v != nil {
		_u.SetNotes(*v)
	}
	return _u
}

// ClearNotes clears the value of the "notes" field.
func (_u *SubscriptionOrderUpdate) ClearNotes() *SubscriptionOrderUpdate {
	_u.mutation.ClearNotes()
	return _u
}

// SetUser sets the "user" edge to the User entity.
func (_u *SubscriptionOrderUpdate) SetUser(v *User) *SubscriptionOrderUpdate {
	return _u.SetUserID(v.ID)
}

// SetGroup sets the "group" edge to the Group entity.
func (_u *SubscriptionOrderUpdate) SetGroup(v *Group) *SubscriptionOrderUpdate {
	return _u.SetGroupID(v.ID)
}

// SetSubscription sets the "subscription" edge to the UserSubscription entity.
func (_u *SubscriptionOrderUpdate) SetSubscription(v *UserSubscription) *SubscriptionOrderUpdate {
	return _u.SetSubscriptionID(v.ID)
}

// Mutation returns the SubscriptionOrderMutation object of the builder.
func (_u *SubscriptionOrderUpdate) Mutation() *SubscriptionOrderMutation {
	return _u.mutation
}

// ClearUser clears the "user" edge to the User entity.
func (_u *SubscriptionOrderUpdate) ClearUser() *SubscriptionOrderUpdate {
	_u.mutation.ClearUser()
	return _u
}

// ClearGroup clears the "group" edge to the Group entity.
func (_u *SubscriptionOrderUpdate) ClearGroup() *SubscriptionOrderUpdate {
	_u.mutation.ClearGroup()
	return _u
}

// ClearSubscription clears the "subscription" edge to the UserSubscription entity.
func (_u *SubscriptionOrderUpdate) ClearSubscription() *SubscriptionOrderUpdate {
	_u.mutation.ClearSubscription()
	return _u
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *SubscriptionOrderUpdate) Save(ctx context.Context) (int, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *SubscriptionOrderUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *SubscriptionOrderUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *SubscriptionOrderUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *SubscriptionOrderUpdate) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := subscriptionorder.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *SubscriptionOrderUpdate) check() error {
	if v, ok := _u.mutation.OrderNo(); ok {
		if err := subscriptionorder.OrderNoValidator(v); err != nil {
			return &ValidationError{Name: "order_no", err: fmt.Errorf(`ent: validator failed for field "SubscriptionOrder.order_no": %w`, err)}
		}
	}
	if v, ok := _u.mutation.PaymentProvider(); ok {
		if err := subscriptionorder.PaymentProviderValidator(v); err != nil {
			return &ValidationError{Name: "payment_provider", err: fmt.Errorf(`ent: validator failed for field "SubscriptionOrder.payment_provider": %w`, err)}
		}
	}
	if v, ok := _u.mutation.PaymentOpenOrderID(); ok {
		if err := subscriptionorder.PaymentOpenOrderIDValidator(v); err != nil {
			return &ValidationError{Name: "payment_open_order_id", err: fmt.Errorf(`ent: validator failed for field "SubscriptionOrder.payment_open_order_id": %w`, err)}
		}
	}
	if v, ok := _u.mutation.PaymentTransactionID(); ok {
		if err := subscriptionorder.PaymentTransactionIDValidator(v); err != nil {
			return &ValidationError{Name: "payment_transaction_id", err: fmt.Errorf(`ent: validator failed for field "SubscriptionOrder.payment_transaction_id": %w`, err)}
		}
	}
	if v, ok := _u.mutation.PaymentPlugin(); ok {
		if err := subscriptionorder.PaymentPluginValidator(v); err != nil {
			return &ValidationError{Name: "payment_plugin", err: fmt.Errorf(`ent: validator failed for field "SubscriptionOrder.payment_plugin": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Status(); ok {
		if err := subscriptionorder.StatusValidator(v); err != nil {
			return &ValidationError{Name: "status", err: fmt.Errorf(`ent: validator failed for field "SubscriptionOrder.status": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Currency(); ok {
		if err := subscriptionorder.CurrencyValidator(v); err != nil {
			return &ValidationError{Name: "currency", err: fmt.Errorf(`ent: validator failed for field "SubscriptionOrder.currency": %w`, err)}
		}
	}
	if _u.mutation.UserCleared() && len(_u.mutation.UserIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "SubscriptionOrder.user"`)
	}
	if _u.mutation.GroupCleared() && len(_u.mutation.GroupIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "SubscriptionOrder.group"`)
	}
	return nil
}

func (_u *SubscriptionOrderUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(subscriptionorder.Table, subscriptionorder.Columns, sqlgraph.NewFieldSpec(subscriptionorder.FieldID, field.TypeInt64))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(subscriptionorder.FieldUpdatedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.OrderNo(); ok {
		_spec.SetField(subscriptionorder.FieldOrderNo, field.TypeString, value)
	}
	if value, ok := _u.mutation.PaymentProvider(); ok {
		_spec.SetField(subscriptionorder.FieldPaymentProvider, field.TypeString, value)
	}
	if value, ok := _u.mutation.PaymentURL(); ok {
		_spec.SetField(subscriptionorder.FieldPaymentURL, field.TypeString, value)
	}
	if _u.mutation.PaymentURLCleared() {
		_spec.ClearField(subscriptionorder.FieldPaymentURL, field.TypeString)
	}
	if value, ok := _u.mutation.PaymentQrcode(); ok {
		_spec.SetField(subscriptionorder.FieldPaymentQrcode, field.TypeString, value)
	}
	if _u.mutation.PaymentQrcodeCleared() {
		_spec.ClearField(subscriptionorder.FieldPaymentQrcode, field.TypeString)
	}
	if value, ok := _u.mutation.PaymentOpenOrderID(); ok {
		_spec.SetField(subscriptionorder.FieldPaymentOpenOrderID, field.TypeString, value)
	}
	if _u.mutation.PaymentOpenOrderIDCleared() {
		_spec.ClearField(subscriptionorder.FieldPaymentOpenOrderID, field.TypeString)
	}
	if value, ok := _u.mutation.PaymentTransactionID(); ok {
		_spec.SetField(subscriptionorder.FieldPaymentTransactionID, field.TypeString, value)
	}
	if _u.mutation.PaymentTransactionIDCleared() {
		_spec.ClearField(subscriptionorder.FieldPaymentTransactionID, field.TypeString)
	}
	if value, ok := _u.mutation.PaymentPlugin(); ok {
		_spec.SetField(subscriptionorder.FieldPaymentPlugin, field.TypeString, value)
	}
	if _u.mutation.PaymentPluginCleared() {
		_spec.ClearField(subscriptionorder.FieldPaymentPlugin, field.TypeString)
	}
	if value, ok := _u.mutation.Status(); ok {
		_spec.SetField(subscriptionorder.FieldStatus, field.TypeString, value)
	}
	if value, ok := _u.mutation.Amount(); ok {
		_spec.SetField(subscriptionorder.FieldAmount, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedAmount(); ok {
		_spec.AddField(subscriptionorder.FieldAmount, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.Currency(); ok {
		_spec.SetField(subscriptionorder.FieldCurrency, field.TypeString, value)
	}
	if value, ok := _u.mutation.ValidityDays(); ok {
		_spec.SetField(subscriptionorder.FieldValidityDays, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedValidityDays(); ok {
		_spec.AddField(subscriptionorder.FieldValidityDays, field.TypeInt, value)
	}
	if value, ok := _u.mutation.PaidAt(); ok {
		_spec.SetField(subscriptionorder.FieldPaidAt, field.TypeTime, value)
	}
	if _u.mutation.PaidAtCleared() {
		_spec.ClearField(subscriptionorder.FieldPaidAt, field.TypeTime)
	}
	if value, ok := _u.mutation.CanceledAt(); ok {
		_spec.SetField(subscriptionorder.FieldCanceledAt, field.TypeTime, value)
	}
	if _u.mutation.CanceledAtCleared() {
		_spec.ClearField(subscriptionorder.FieldCanceledAt, field.TypeTime)
	}
	if value, ok := _u.mutation.Notes(); ok {
		_spec.SetField(subscriptionorder.FieldNotes, field.TypeString, value)
	}
	if _u.mutation.NotesCleared() {
		_spec.ClearField(subscriptionorder.FieldNotes, field.TypeString)
	}
	if _u.mutation.UserCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   subscriptionorder.UserTable,
			Columns: []string{subscriptionorder.UserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt64),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.UserIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   subscriptionorder.UserTable,
			Columns: []string{subscriptionorder.UserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.GroupCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   subscriptionorder.GroupTable,
			Columns: []string{subscriptionorder.GroupColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(group.FieldID, field.TypeInt64),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.GroupIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   subscriptionorder.GroupTable,
			Columns: []string{subscriptionorder.GroupColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(group.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.SubscriptionCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   subscriptionorder.SubscriptionTable,
			Columns: []string{subscriptionorder.SubscriptionColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(usersubscription.FieldID, field.TypeInt64),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.SubscriptionIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   subscriptionorder.SubscriptionTable,
			Columns: []string{subscriptionorder.SubscriptionColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(usersubscription.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{subscriptionorder.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// SubscriptionOrderUpdateOne is the builder for updating a single SubscriptionOrder entity.
type SubscriptionOrderUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *SubscriptionOrderMutation
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *SubscriptionOrderUpdateOne) SetUpdatedAt(v time.Time) *SubscriptionOrderUpdateOne {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetOrderNo sets the "order_no" field.
func (_u *SubscriptionOrderUpdateOne) SetOrderNo(v string) *SubscriptionOrderUpdateOne {
	_u.mutation.SetOrderNo(v)
	return _u
}

// SetNillableOrderNo sets the "order_no" field if the given value is not nil.
func (_u *SubscriptionOrderUpdateOne) SetNillableOrderNo(v *string) *SubscriptionOrderUpdateOne {
	if v != nil {
		_u.SetOrderNo(*v)
	}
	return _u
}

// SetUserID sets the "user_id" field.
func (_u *SubscriptionOrderUpdateOne) SetUserID(v int64) *SubscriptionOrderUpdateOne {
	_u.mutation.SetUserID(v)
	return _u
}

// SetNillableUserID sets the "user_id" field if the given value is not nil.
func (_u *SubscriptionOrderUpdateOne) SetNillableUserID(v *int64) *SubscriptionOrderUpdateOne {
	if v != nil {
		_u.SetUserID(*v)
	}
	return _u
}

// SetGroupID sets the "group_id" field.
func (_u *SubscriptionOrderUpdateOne) SetGroupID(v int64) *SubscriptionOrderUpdateOne {
	_u.mutation.SetGroupID(v)
	return _u
}

// SetNillableGroupID sets the "group_id" field if the given value is not nil.
func (_u *SubscriptionOrderUpdateOne) SetNillableGroupID(v *int64) *SubscriptionOrderUpdateOne {
	if v != nil {
		_u.SetGroupID(*v)
	}
	return _u
}

// SetSubscriptionID sets the "subscription_id" field.
func (_u *SubscriptionOrderUpdateOne) SetSubscriptionID(v int64) *SubscriptionOrderUpdateOne {
	_u.mutation.SetSubscriptionID(v)
	return _u
}

// SetNillableSubscriptionID sets the "subscription_id" field if the given value is not nil.
func (_u *SubscriptionOrderUpdateOne) SetNillableSubscriptionID(v *int64) *SubscriptionOrderUpdateOne {
	if v != nil {
		_u.SetSubscriptionID(*v)
	}
	return _u
}

// ClearSubscriptionID clears the value of the "subscription_id" field.
func (_u *SubscriptionOrderUpdateOne) ClearSubscriptionID() *SubscriptionOrderUpdateOne {
	_u.mutation.ClearSubscriptionID()
	return _u
}

// SetPaymentProvider sets the "payment_provider" field.
func (_u *SubscriptionOrderUpdateOne) SetPaymentProvider(v string) *SubscriptionOrderUpdateOne {
	_u.mutation.SetPaymentProvider(v)
	return _u
}

// SetNillablePaymentProvider sets the "payment_provider" field if the given value is not nil.
func (_u *SubscriptionOrderUpdateOne) SetNillablePaymentProvider(v *string) *SubscriptionOrderUpdateOne {
	if v != nil {
		_u.SetPaymentProvider(*v)
	}
	return _u
}

// SetPaymentURL sets the "payment_url" field.
func (_u *SubscriptionOrderUpdateOne) SetPaymentURL(v string) *SubscriptionOrderUpdateOne {
	_u.mutation.SetPaymentURL(v)
	return _u
}

// SetNillablePaymentURL sets the "payment_url" field if the given value is not nil.
func (_u *SubscriptionOrderUpdateOne) SetNillablePaymentURL(v *string) *SubscriptionOrderUpdateOne {
	if v != nil {
		_u.SetPaymentURL(*v)
	}
	return _u
}

// ClearPaymentURL clears the value of the "payment_url" field.
func (_u *SubscriptionOrderUpdateOne) ClearPaymentURL() *SubscriptionOrderUpdateOne {
	_u.mutation.ClearPaymentURL()
	return _u
}

// SetPaymentQrcode sets the "payment_qrcode" field.
func (_u *SubscriptionOrderUpdateOne) SetPaymentQrcode(v string) *SubscriptionOrderUpdateOne {
	_u.mutation.SetPaymentQrcode(v)
	return _u
}

// SetNillablePaymentQrcode sets the "payment_qrcode" field if the given value is not nil.
func (_u *SubscriptionOrderUpdateOne) SetNillablePaymentQrcode(v *string) *SubscriptionOrderUpdateOne {
	if v != nil {
		_u.SetPaymentQrcode(*v)
	}
	return _u
}

// ClearPaymentQrcode clears the value of the "payment_qrcode" field.
func (_u *SubscriptionOrderUpdateOne) ClearPaymentQrcode() *SubscriptionOrderUpdateOne {
	_u.mutation.ClearPaymentQrcode()
	return _u
}

// SetPaymentOpenOrderID sets the "payment_open_order_id" field.
func (_u *SubscriptionOrderUpdateOne) SetPaymentOpenOrderID(v string) *SubscriptionOrderUpdateOne {
	_u.mutation.SetPaymentOpenOrderID(v)
	return _u
}

// SetNillablePaymentOpenOrderID sets the "payment_open_order_id" field if the given value is not nil.
func (_u *SubscriptionOrderUpdateOne) SetNillablePaymentOpenOrderID(v *string) *SubscriptionOrderUpdateOne {
	if v != nil {
		_u.SetPaymentOpenOrderID(*v)
	}
	return _u
}

// ClearPaymentOpenOrderID clears the value of the "payment_open_order_id" field.
func (_u *SubscriptionOrderUpdateOne) ClearPaymentOpenOrderID() *SubscriptionOrderUpdateOne {
	_u.mutation.ClearPaymentOpenOrderID()
	return _u
}

// SetPaymentTransactionID sets the "payment_transaction_id" field.
func (_u *SubscriptionOrderUpdateOne) SetPaymentTransactionID(v string) *SubscriptionOrderUpdateOne {
	_u.mutation.SetPaymentTransactionID(v)
	return _u
}

// SetNillablePaymentTransactionID sets the "payment_transaction_id" field if the given value is not nil.
func (_u *SubscriptionOrderUpdateOne) SetNillablePaymentTransactionID(v *string) *SubscriptionOrderUpdateOne {
	if v != nil {
		_u.SetPaymentTransactionID(*v)
	}
	return _u
}

// ClearPaymentTransactionID clears the value of the "payment_transaction_id" field.
func (_u *SubscriptionOrderUpdateOne) ClearPaymentTransactionID() *SubscriptionOrderUpdateOne {
	_u.mutation.ClearPaymentTransactionID()
	return _u
}

// SetPaymentPlugin sets the "payment_plugin" field.
func (_u *SubscriptionOrderUpdateOne) SetPaymentPlugin(v string) *SubscriptionOrderUpdateOne {
	_u.mutation.SetPaymentPlugin(v)
	return _u
}

// SetNillablePaymentPlugin sets the "payment_plugin" field if the given value is not nil.
func (_u *SubscriptionOrderUpdateOne) SetNillablePaymentPlugin(v *string) *SubscriptionOrderUpdateOne {
	if v != nil {
		_u.SetPaymentPlugin(*v)
	}
	return _u
}

// ClearPaymentPlugin clears the value of the "payment_plugin" field.
func (_u *SubscriptionOrderUpdateOne) ClearPaymentPlugin() *SubscriptionOrderUpdateOne {
	_u.mutation.ClearPaymentPlugin()
	return _u
}

// SetStatus sets the "status" field.
func (_u *SubscriptionOrderUpdateOne) SetStatus(v string) *SubscriptionOrderUpdateOne {
	_u.mutation.SetStatus(v)
	return _u
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_u *SubscriptionOrderUpdateOne) SetNillableStatus(v *string) *SubscriptionOrderUpdateOne {
	if v != nil {
		_u.SetStatus(*v)
	}
	return _u
}

// SetAmount sets the "amount" field.
func (_u *SubscriptionOrderUpdateOne) SetAmount(v float64) *SubscriptionOrderUpdateOne {
	_u.mutation.ResetAmount()
	_u.mutation.SetAmount(v)
	return _u
}

// SetNillableAmount sets the "amount" field if the given value is not nil.
func (_u *SubscriptionOrderUpdateOne) SetNillableAmount(v *float64) *SubscriptionOrderUpdateOne {
	if v != nil {
		_u.SetAmount(*v)
	}
	return _u
}

// AddAmount adds value to the "amount" field.
func (_u *SubscriptionOrderUpdateOne) AddAmount(v float64) *SubscriptionOrderUpdateOne {
	_u.mutation.AddAmount(v)
	return _u
}

// SetCurrency sets the "currency" field.
func (_u *SubscriptionOrderUpdateOne) SetCurrency(v string) *SubscriptionOrderUpdateOne {
	_u.mutation.SetCurrency(v)
	return _u
}

// SetNillableCurrency sets the "currency" field if the given value is not nil.
func (_u *SubscriptionOrderUpdateOne) SetNillableCurrency(v *string) *SubscriptionOrderUpdateOne {
	if v != nil {
		_u.SetCurrency(*v)
	}
	return _u
}

// SetValidityDays sets the "validity_days" field.
func (_u *SubscriptionOrderUpdateOne) SetValidityDays(v int) *SubscriptionOrderUpdateOne {
	_u.mutation.ResetValidityDays()
	_u.mutation.SetValidityDays(v)
	return _u
}

// SetNillableValidityDays sets the "validity_days" field if the given value is not nil.
func (_u *SubscriptionOrderUpdateOne) SetNillableValidityDays(v *int) *SubscriptionOrderUpdateOne {
	if v != nil {
		_u.SetValidityDays(*v)
	}
	return _u
}

// AddValidityDays adds value to the "validity_days" field.
func (_u *SubscriptionOrderUpdateOne) AddValidityDays(v int) *SubscriptionOrderUpdateOne {
	_u.mutation.AddValidityDays(v)
	return _u
}

// SetPaidAt sets the "paid_at" field.
func (_u *SubscriptionOrderUpdateOne) SetPaidAt(v time.Time) *SubscriptionOrderUpdateOne {
	_u.mutation.SetPaidAt(v)
	return _u
}

// SetNillablePaidAt sets the "paid_at" field if the given value is not nil.
func (_u *SubscriptionOrderUpdateOne) SetNillablePaidAt(v *time.Time) *SubscriptionOrderUpdateOne {
	if v != nil {
		_u.SetPaidAt(*v)
	}
	return _u
}

// ClearPaidAt clears the value of the "paid_at" field.
func (_u *SubscriptionOrderUpdateOne) ClearPaidAt() *SubscriptionOrderUpdateOne {
	_u.mutation.ClearPaidAt()
	return _u
}

// SetCanceledAt sets the "canceled_at" field.
func (_u *SubscriptionOrderUpdateOne) SetCanceledAt(v time.Time) *SubscriptionOrderUpdateOne {
	_u.mutation.SetCanceledAt(v)
	return _u
}

// SetNillableCanceledAt sets the "canceled_at" field if the given value is not nil.
func (_u *SubscriptionOrderUpdateOne) SetNillableCanceledAt(v *time.Time) *SubscriptionOrderUpdateOne {
	if v != nil {
		_u.SetCanceledAt(*v)
	}
	return _u
}

// ClearCanceledAt clears the value of the "canceled_at" field.
func (_u *SubscriptionOrderUpdateOne) ClearCanceledAt() *SubscriptionOrderUpdateOne {
	_u.mutation.ClearCanceledAt()
	return _u
}

// SetNotes sets the "notes" field.
func (_u *SubscriptionOrderUpdateOne) SetNotes(v string) *SubscriptionOrderUpdateOne {
	_u.mutation.SetNotes(v)
	return _u
}

// SetNillableNotes sets the "notes" field if the given value is not nil.
func (_u *SubscriptionOrderUpdateOne) SetNillableNotes(v *string) *SubscriptionOrderUpdateOne {
	if v != nil {
		_u.SetNotes(*v)
	}
	return _u
}

// ClearNotes clears the value of the "notes" field.
func (_u *SubscriptionOrderUpdateOne) ClearNotes() *SubscriptionOrderUpdateOne {
	_u.mutation.ClearNotes()
	return _u
}

// SetUser sets the "user" edge to the User entity.
func (_u *SubscriptionOrderUpdateOne) SetUser(v *User) *SubscriptionOrderUpdateOne {
	return _u.SetUserID(v.ID)
}

// SetGroup sets the "group" edge to the Group entity.
func (_u *SubscriptionOrderUpdateOne) SetGroup(v *Group) *SubscriptionOrderUpdateOne {
	return _u.SetGroupID(v.ID)
}

// SetSubscription sets the "subscription" edge to the UserSubscription entity.
func (_u *SubscriptionOrderUpdateOne) SetSubscription(v *UserSubscription) *SubscriptionOrderUpdateOne {
	return _u.SetSubscriptionID(v.ID)
}

// Mutation returns the SubscriptionOrderMutation object of the builder.
func (_u *SubscriptionOrderUpdateOne) Mutation() *SubscriptionOrderMutation {
	return _u.mutation
}

// ClearUser clears the "user" edge to the User entity.
func (_u *SubscriptionOrderUpdateOne) ClearUser() *SubscriptionOrderUpdateOne {
	_u.mutation.ClearUser()
	return _u
}

// ClearGroup clears the "group" edge to the Group entity.
func (_u *SubscriptionOrderUpdateOne) ClearGroup() *SubscriptionOrderUpdateOne {
	_u.mutation.ClearGroup()
	return _u
}

// ClearSubscription clears the "subscription" edge to the UserSubscription entity.
func (_u *SubscriptionOrderUpdateOne) ClearSubscription() *SubscriptionOrderUpdateOne {
	_u.mutation.ClearSubscription()
	return _u
}

// Where appends a list predicates to the SubscriptionOrderUpdate builder.
func (_u *SubscriptionOrderUpdateOne) Where(ps ...predicate.SubscriptionOrder) *SubscriptionOrderUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *SubscriptionOrderUpdateOne) Select(field string, fields ...string) *SubscriptionOrderUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated SubscriptionOrder entity.
func (_u *SubscriptionOrderUpdateOne) Save(ctx context.Context) (*SubscriptionOrder, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *SubscriptionOrderUpdateOne) SaveX(ctx context.Context) *SubscriptionOrder {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *SubscriptionOrderUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *SubscriptionOrderUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *SubscriptionOrderUpdateOne) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := subscriptionorder.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *SubscriptionOrderUpdateOne) check() error {
	if v, ok := _u.mutation.OrderNo(); ok {
		if err := subscriptionorder.OrderNoValidator(v); err != nil {
			return &ValidationError{Name: "order_no", err: fmt.Errorf(`ent: validator failed for field "SubscriptionOrder.order_no": %w`, err)}
		}
	}
	if v, ok := _u.mutation.PaymentProvider(); ok {
		if err := subscriptionorder.PaymentProviderValidator(v); err != nil {
			return &ValidationError{Name: "payment_provider", err: fmt.Errorf(`ent: validator failed for field "SubscriptionOrder.payment_provider": %w`, err)}
		}
	}
	if v, ok := _u.mutation.PaymentOpenOrderID(); ok {
		if err := subscriptionorder.PaymentOpenOrderIDValidator(v); err != nil {
			return &ValidationError{Name: "payment_open_order_id", err: fmt.Errorf(`ent: validator failed for field "SubscriptionOrder.payment_open_order_id": %w`, err)}
		}
	}
	if v, ok := _u.mutation.PaymentTransactionID(); ok {
		if err := subscriptionorder.PaymentTransactionIDValidator(v); err != nil {
			return &ValidationError{Name: "payment_transaction_id", err: fmt.Errorf(`ent: validator failed for field "SubscriptionOrder.payment_transaction_id": %w`, err)}
		}
	}
	if v, ok := _u.mutation.PaymentPlugin(); ok {
		if err := subscriptionorder.PaymentPluginValidator(v); err != nil {
			return &ValidationError{Name: "payment_plugin", err: fmt.Errorf(`ent: validator failed for field "SubscriptionOrder.payment_plugin": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Status(); ok {
		if err := subscriptionorder.StatusValidator(v); err != nil {
			return &ValidationError{Name: "status", err: fmt.Errorf(`ent: validator failed for field "SubscriptionOrder.status": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Currency(); ok {
		if err := subscriptionorder.CurrencyValidator(v); err != nil {
			return &ValidationError{Name: "currency", err: fmt.Errorf(`ent: validator failed for field "SubscriptionOrder.currency": %w`, err)}
		}
	}
	if _u.mutation.UserCleared() && len(_u.mutation.UserIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "SubscriptionOrder.user"`)
	}
	if _u.mutation.GroupCleared() && len(_u.mutation.GroupIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "SubscriptionOrder.group"`)
	}
	return nil
}

func (_u *SubscriptionOrderUpdateOne) sqlSave(ctx context.Context) (_node *SubscriptionOrder, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(subscriptionorder.Table, subscriptionorder.Columns, sqlgraph.NewFieldSpec(subscriptionorder.FieldID, field.TypeInt64))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "SubscriptionOrder.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, subscriptionorder.FieldID)
		for _, f := range fields {
			if !subscriptionorder.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != subscriptionorder.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(subscriptionorder.FieldUpdatedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.OrderNo(); ok {
		_spec.SetField(subscriptionorder.FieldOrderNo, field.TypeString, value)
	}
	if value, ok := _u.mutation.PaymentProvider(); ok {
		_spec.SetField(subscriptionorder.FieldPaymentProvider, field.TypeString, value)
	}
	if value, ok := _u.mutation.PaymentURL(); ok {
		_spec.SetField(subscriptionorder.FieldPaymentURL, field.TypeString, value)
	}
	if _u.mutation.PaymentURLCleared() {
		_spec.ClearField(subscriptionorder.FieldPaymentURL, field.TypeString)
	}
	if value, ok := _u.mutation.PaymentQrcode(); ok {
		_spec.SetField(subscriptionorder.FieldPaymentQrcode, field.TypeString, value)
	}
	if _u.mutation.PaymentQrcodeCleared() {
		_spec.ClearField(subscriptionorder.FieldPaymentQrcode, field.TypeString)
	}
	if value, ok := _u.mutation.PaymentOpenOrderID(); ok {
		_spec.SetField(subscriptionorder.FieldPaymentOpenOrderID, field.TypeString, value)
	}
	if _u.mutation.PaymentOpenOrderIDCleared() {
		_spec.ClearField(subscriptionorder.FieldPaymentOpenOrderID, field.TypeString)
	}
	if value, ok := _u.mutation.PaymentTransactionID(); ok {
		_spec.SetField(subscriptionorder.FieldPaymentTransactionID, field.TypeString, value)
	}
	if _u.mutation.PaymentTransactionIDCleared() {
		_spec.ClearField(subscriptionorder.FieldPaymentTransactionID, field.TypeString)
	}
	if value, ok := _u.mutation.PaymentPlugin(); ok {
		_spec.SetField(subscriptionorder.FieldPaymentPlugin, field.TypeString, value)
	}
	if _u.mutation.PaymentPluginCleared() {
		_spec.ClearField(subscriptionorder.FieldPaymentPlugin, field.TypeString)
	}
	if value, ok := _u.mutation.Status(); ok {
		_spec.SetField(subscriptionorder.FieldStatus, field.TypeString, value)
	}
	if value, ok := _u.mutation.Amount(); ok {
		_spec.SetField(subscriptionorder.FieldAmount, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedAmount(); ok {
		_spec.AddField(subscriptionorder.FieldAmount, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.Currency(); ok {
		_spec.SetField(subscriptionorder.FieldCurrency, field.TypeString, value)
	}
	if value, ok := _u.mutation.ValidityDays(); ok {
		_spec.SetField(subscriptionorder.FieldValidityDays, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedValidityDays(); ok {
		_spec.AddField(subscriptionorder.FieldValidityDays, field.TypeInt, value)
	}
	if value, ok := _u.mutation.PaidAt(); ok {
		_spec.SetField(subscriptionorder.FieldPaidAt, field.TypeTime, value)
	}
	if _u.mutation.PaidAtCleared() {
		_spec.ClearField(subscriptionorder.FieldPaidAt, field.TypeTime)
	}
	if value, ok := _u.mutation.CanceledAt(); ok {
		_spec.SetField(subscriptionorder.FieldCanceledAt, field.TypeTime, value)
	}
	if _u.mutation.CanceledAtCleared() {
		_spec.ClearField(subscriptionorder.FieldCanceledAt, field.TypeTime)
	}
	if value, ok := _u.mutation.Notes(); ok {
		_spec.SetField(subscriptionorder.FieldNotes, field.TypeString, value)
	}
	if _u.mutation.NotesCleared() {
		_spec.ClearField(subscriptionorder.FieldNotes, field.TypeString)
	}
	if _u.mutation.UserCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   subscriptionorder.UserTable,
			Columns: []string{subscriptionorder.UserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt64),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.UserIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   subscriptionorder.UserTable,
			Columns: []string{subscriptionorder.UserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.GroupCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   subscriptionorder.GroupTable,
			Columns: []string{subscriptionorder.GroupColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(group.FieldID, field.TypeInt64),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.GroupIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   subscriptionorder.GroupTable,
			Columns: []string{subscriptionorder.GroupColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(group.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.SubscriptionCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   subscriptionorder.SubscriptionTable,
			Columns: []string{subscriptionorder.SubscriptionColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(usersubscription.FieldID, field.TypeInt64),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.SubscriptionIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   subscriptionorder.SubscriptionTable,
			Columns: []string{subscriptionorder.SubscriptionColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(usersubscription.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_node = &SubscriptionOrder{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{subscriptionorder.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
