// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/Wei-Shaw/sub2api/ent/group"
	"github.com/Wei-Shaw/sub2api/ent/subscriptionorder"
	"github.com/Wei-Shaw/sub2api/ent/user"
	"github.com/Wei-Shaw/sub2api/ent/usersubscription"
)

// SubscriptionOrderCreate is the builder for creating a SubscriptionOrder entity.
type SubscriptionOrderCreate struct {
	config
	mutation *SubscriptionOrderMutation
	hooks    []Hook
	conflict []sql.ConflictOption
}

// SetCreatedAt sets the "created_at" field.
func (_c *SubscriptionOrderCreate) SetCreatedAt(v time.Time) *SubscriptionOrderCreate {
	_c.mutation.SetCreatedAt(v)
	return _c
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_c *SubscriptionOrderCreate) SetNillableCreatedAt(v *time.Time) *SubscriptionOrderCreate {
	if v != nil {
		_c.SetCreatedAt(*v)
	}
	return _c
}

// SetUpdatedAt sets the "updated_at" field.
func (_c *SubscriptionOrderCreate) SetUpdatedAt(v time.Time) *SubscriptionOrderCreate {
	_c.mutation.SetUpdatedAt(v)
	return _c
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (_c *SubscriptionOrderCreate) SetNillableUpdatedAt(v *time.Time) *SubscriptionOrderCreate {
	if v != nil {
		_c.SetUpdatedAt(*v)
	}
	return _c
}

// SetOrderNo sets the "order_no" field.
func (_c *SubscriptionOrderCreate) SetOrderNo(v string) *SubscriptionOrderCreate {
	_c.mutation.SetOrderNo(v)
	return _c
}

// SetUserID sets the "user_id" field.
func (_c *SubscriptionOrderCreate) SetUserID(v int64) *SubscriptionOrderCreate {
	_c.mutation.SetUserID(v)
	return _c
}

// SetGroupID sets the "group_id" field.
func (_c *SubscriptionOrderCreate) SetGroupID(v int64) *SubscriptionOrderCreate {
	_c.mutation.SetGroupID(v)
	return _c
}

// SetSubscriptionID sets the "subscription_id" field.
func (_c *SubscriptionOrderCreate) SetSubscriptionID(v int64) *SubscriptionOrderCreate {
	_c.mutation.SetSubscriptionID(v)
	return _c
}

// SetNillableSubscriptionID sets the "subscription_id" field if the given value is not nil.
func (_c *SubscriptionOrderCreate) SetNillableSubscriptionID(v *int64) *SubscriptionOrderCreate {
	if v != nil {
		_c.SetSubscriptionID(*v)
	}
	return _c
}

// SetPaymentProvider sets the "payment_provider" field.
func (_c *SubscriptionOrderCreate) SetPaymentProvider(v string) *SubscriptionOrderCreate {
	_c.mutation.SetPaymentProvider(v)
	return _c
}

// SetNillablePaymentProvider sets the "payment_provider" field if the given value is not nil.
func (_c *SubscriptionOrderCreate) SetNillablePaymentProvider(v *string) *SubscriptionOrderCreate {
	if v != nil {
		_c.SetPaymentProvider(*v)
	}
	return _c
}

// SetPaymentURL sets the "payment_url" field.
func (_c *SubscriptionOrderCreate) SetPaymentURL(v string) *SubscriptionOrderCreate {
	_c.mutation.SetPaymentURL(v)
	return _c
}

// SetNillablePaymentURL sets the "payment_url" field if the given value is not nil.
func (_c *SubscriptionOrderCreate) SetNillablePaymentURL(v *string) *SubscriptionOrderCreate {
	if v != nil {
		_c.SetPaymentURL(*v)
	}
	return _c
}

// SetPaymentQrcode sets the "payment_qrcode" field.
func (_c *SubscriptionOrderCreate) SetPaymentQrcode(v string) *SubscriptionOrderCreate {
	_c.mutation.SetPaymentQrcode(v)
	return _c
}

// SetNillablePaymentQrcode sets the "payment_qrcode" field if the given value is not nil.
func (_c *SubscriptionOrderCreate) SetNillablePaymentQrcode(v *string) *SubscriptionOrderCreate {
	if v != nil {
		_c.SetPaymentQrcode(*v)
	}
	return _c
}

// SetPaymentOpenOrderID sets the "payment_open_order_id" field.
func (_c *SubscriptionOrderCreate) SetPaymentOpenOrderID(v string) *SubscriptionOrderCreate {
	_c.mutation.SetPaymentOpenOrderID(v)
	return _c
}

// SetNillablePaymentOpenOrderID sets the "payment_open_order_id" field if the given value is not nil.
func (_c *SubscriptionOrderCreate) SetNillablePaymentOpenOrderID(v *string) *SubscriptionOrderCreate {
	if v != nil {
		_c.SetPaymentOpenOrderID(*v)
	}
	return _c
}

// SetPaymentTransactionID sets the "payment_transaction_id" field.
func (_c *SubscriptionOrderCreate) SetPaymentTransactionID(v string) *SubscriptionOrderCreate {
	_c.mutation.SetPaymentTransactionID(v)
	return _c
}

// SetNillablePaymentTransactionID sets the "payment_transaction_id" field if the given value is not nil.
func (_c *SubscriptionOrderCreate) SetNillablePaymentTransactionID(v *string) *SubscriptionOrderCreate {
	if v != nil {
		_c.SetPaymentTransactionID(*v)
	}
	return _c
}

// SetPaymentPlugin sets the "payment_plugin" field.
func (_c *SubscriptionOrderCreate) SetPaymentPlugin(v string) *SubscriptionOrderCreate {
	_c.mutation.SetPaymentPlugin(v)
	return _c
}

// SetNillablePaymentPlugin sets the "payment_plugin" field if the given value is not nil.
func (_c *SubscriptionOrderCreate) SetNillablePaymentPlugin(v *string) *SubscriptionOrderCreate {
	if v != nil {
		_c.SetPaymentPlugin(*v)
	}
	return _c
}

// SetStatus sets the "status" field.
func (_c *SubscriptionOrderCreate) SetStatus(v string) *SubscriptionOrderCreate {
	_c.mutation.SetStatus(v)
	return _c
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_c *SubscriptionOrderCreate) SetNillableStatus(v *string) *SubscriptionOrderCreate {
	if v != nil {
		_c.SetStatus(*v)
	}
	return _c
}

// SetAmount sets the "amount" field.
func (_c *SubscriptionOrderCreate) SetAmount(v float64) *SubscriptionOrderCreate {
	_c.mutation.SetAmount(v)
	return _c
}

// SetNillableAmount sets the "amount" field if the given value is not nil.
func (_c *SubscriptionOrderCreate) SetNillableAmount(v *float64) *SubscriptionOrderCreate {
	if v != nil {
		_c.SetAmount(*v)
	}
	return _c
}

// SetCurrency sets the "currency" field.
func (_c *SubscriptionOrderCreate) SetCurrency(v string) *SubscriptionOrderCreate {
	_c.mutation.SetCurrency(v)
	return _c
}

// SetNillableCurrency sets the "currency" field if the given value is not nil.
func (_c *SubscriptionOrderCreate) SetNillableCurrency(v *string) *SubscriptionOrderCreate {
	if v != nil {
		_c.SetCurrency(*v)
	}
	return _c
}

// SetValidityDays sets the "validity_days" field.
func (_c *SubscriptionOrderCreate) SetValidityDays(v int) *SubscriptionOrderCreate {
	_c.mutation.SetValidityDays(v)
	return _c
}

// SetNillableValidityDays sets the "validity_days" field if the given value is not nil.
func (_c *SubscriptionOrderCreate) SetNillableValidityDays(v *int) *SubscriptionOrderCreate {
	if v != nil {
		_c.SetValidityDays(*v)
	}
	return _c
}

// SetPaidAt sets the "paid_at" field.
func (_c *SubscriptionOrderCreate) SetPaidAt(v time.Time) *SubscriptionOrderCreate {
	_c.mutation.SetPaidAt(v)
	return _c
}

// SetNillablePaidAt sets the "paid_at" field if the given value is not nil.
func (_c *SubscriptionOrderCreate) SetNillablePaidAt(v *time.Time) *SubscriptionOrderCreate {
	if v != nil {
		_c.SetPaidAt(*v)
	}
	return _c
}

// SetCanceledAt sets the "canceled_at" field.
func (_c *SubscriptionOrderCreate) SetCanceledAt(v time.Time) *SubscriptionOrderCreate {
	_c.mutation.SetCanceledAt(v)
	return _c
}

// SetNillableCanceledAt sets the "canceled_at" field if the given value is not nil.
func (_c *SubscriptionOrderCreate) SetNillableCanceledAt(v *time.Time) *SubscriptionOrderCreate {
	if v != nil {
		_c.SetCanceledAt(*v)
	}
	return _c
}

// SetNotes sets the "notes" field.
func (_c *SubscriptionOrderCreate) SetNotes(v string) *SubscriptionOrderCreate {
	_c.mutation.SetNotes(v)
	return _c
}

// SetNillableNotes sets the "notes" field if the given value is not nil.
func (_c *SubscriptionOrderCreate) SetNillableNotes(v *string) *SubscriptionOrderCreate {
	if v != nil {
		_c.SetNotes(*v)
	}
	return _c
}

// SetUser sets the "user" edge to the User entity.
func (_c *SubscriptionOrderCreate) SetUser(v *User) *SubscriptionOrderCreate {
	return _c.SetUserID(v.ID)
}

// SetGroup sets the "group" edge to the Group entity.
func (_c *SubscriptionOrderCreate) SetGroup(v *Group) *SubscriptionOrderCreate {
	return _c.SetGroupID(v.ID)
}

// SetSubscription sets the "subscription" edge to the UserSubscription entity.
func (_c *SubscriptionOrderCreate) SetSubscription(v *UserSubscription) *SubscriptionOrderCreate {
	return _c.SetSubscriptionID(v.ID)
}

// Mutation returns the SubscriptionOrderMutation object of the builder.
func (_c *SubscriptionOrderCreate) Mutation() *SubscriptionOrderMutation {
	return _c.mutation
}

// Save creates the SubscriptionOrder in the database.
func (_c *SubscriptionOrderCreate) Save(ctx context.Context) (*SubscriptionOrder, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *SubscriptionOrderCreate) SaveX(ctx context.Context) *SubscriptionOrder {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *SubscriptionOrderCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *SubscriptionOrderCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *SubscriptionOrderCreate) defaults() {
	if _, ok := _c.mutation.CreatedAt(); !ok {
		v := subscriptionorder.DefaultCreatedAt()
		_c.mutation.SetCreatedAt(v)
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		v := subscriptionorder.DefaultUpdatedAt()
		_c.mutation.SetUpdatedAt(v)
	}
	if _, ok := _c.mutation.PaymentProvider(); !ok {
		v := subscriptionorder.DefaultPaymentProvider
		_c.mutation.SetPaymentProvider(v)
	}
	if _, ok := _c.mutation.Status(); !ok {
		v := subscriptionorder.DefaultStatus
		_c.mutation.SetStatus(v)
	}
	if _, ok := _c.mutation.Amount(); !ok {
		v := subscriptionorder.DefaultAmount
		_c.mutation.SetAmount(v)
	}
	if _, ok := _c.mutation.Currency(); !ok {
		v := subscriptionorder.DefaultCurrency
		_c.mutation.SetCurrency(v)
	}
	if _, ok := _c.mutation.ValidityDays(); !ok {
		v := subscriptionorder.DefaultValidityDays
		_c.mutation.SetValidityDays(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *SubscriptionOrderCreate) check() error {
	if _, ok := _c.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "SubscriptionOrder.created_at"`)}
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		return &ValidationError{Name: "updated_at", err: errors.New(`ent: missing required field "SubscriptionOrder.updated_at"`)}
	}
	if _, ok := _c.mutation.OrderNo(); !ok {
		return &ValidationError{Name: "order_no", err: errors.New(`ent: missing required field "SubscriptionOrder.order_no"`)}
	}
	if v, ok := _c.mutation.OrderNo(); ok {
		if err := subscriptionorder.OrderNoValidator(v); err != nil {
			return &ValidationError{Name: "order_no", err: fmt.Errorf(`ent: validator failed for field "SubscriptionOrder.order_no": %w`, err)}
		}
	}
	if _, ok := _c.mutation.UserID(); !ok {
		return &ValidationError{Name: "user_id", err: errors.New(`ent: missing required field "SubscriptionOrder.user_id"`)}
	}
	if _, ok := _c.mutation.GroupID(); !ok {
		return &ValidationError{Name: "group_id", err: errors.New(`ent: missing required field "SubscriptionOrder.group_id"`)}
	}
	if _, ok := _c.mutation.PaymentProvider(); !ok {
		return &ValidationError{Name: "payment_provider", err: errors.New(`ent: missing required field "SubscriptionOrder.payment_provider"`)}
	}
	if v, ok := _c.mutation.PaymentProvider(); ok {
		if err := subscriptionorder.PaymentProviderValidator(v); err != nil {
			return &ValidationError{Name: "payment_provider", err: fmt.Errorf(`ent: validator failed for field "SubscriptionOrder.payment_provider": %w`, err)}
		}
	}
	if v, ok := _c.mutation.PaymentOpenOrderID(); ok {
		if err := subscriptionorder.PaymentOpenOrderIDValidator(v); err != nil {
			return &ValidationError{Name: "payment_open_order_id", err: fmt.Errorf(`ent: validator failed for field "SubscriptionOrder.payment_open_order_id": %w`, err)}
		}
	}
	if v, ok := _c.mutation.PaymentTransactionID(); ok {
		if err := subscriptionorder.PaymentTransactionIDValidator(v); err != nil {
			return &ValidationError{Name: "payment_transaction_id", err: fmt.Errorf(`ent: validator failed for field "SubscriptionOrder.payment_transaction_id": %w`, err)}
		}
	}
	if v, ok := _c.mutation.PaymentPlugin(); ok {
		if err := subscriptionorder.PaymentPluginValidator(v); err != nil {
			return &ValidationError{Name: "payment_plugin", err: fmt.Errorf(`ent: validator failed for field "SubscriptionOrder.payment_plugin": %w`, err)}
		}
	}
	if _, ok := _c.mutation.Status(); !ok {
		return &ValidationError{Name: "status", err: errors.New(`ent: missing required field "SubscriptionOrder.status"`)}
	}
	if v, ok := _c.mutation.Status(); ok {
		if err := subscriptionorder.StatusValidator(v); err != nil {
			return &ValidationError{Name: "status", err: fmt.Errorf(`ent: validator failed for field "SubscriptionOrder.status": %w`, err)}
		}
	}
	if _, ok := _c.mutation.Amount(); !ok {
		return &ValidationError{Name: "amount", err: errors.New(`ent: missing required field "SubscriptionOrder.amount"`)}
	}
	if _, ok := _c.mutation.Currency(); !ok {
		return &ValidationError{Name: "currency", err: errors.New(`ent: missing required field "SubscriptionOrder.currency"`)}
	}
	if v, ok := _c.mutation.Currency(); ok {
		if err := subscriptionorder.CurrencyValidator(v); err != nil {
			return &ValidationError{Name: "currency", err: fmt.Errorf(`ent: validator failed for field "SubscriptionOrder.currency": %w`, err)}
		}
	}
	if _, ok := _c.mutation.ValidityDays(); !ok {
		return &ValidationError{Name: "validity_days", err: errors.New(`ent: missing required field "SubscriptionOrder.validity_days"`)}
	}
	if len(_c.mutation.UserIDs()) == 0 {
		return &ValidationError{Name: "user", err: errors.New(`ent: missing required edge "SubscriptionOrder.user"`)}
	}
	if len(_c.mutation.GroupIDs()) == 0 {
		return &ValidationError{Name: "group", err: errors.New(`ent: missing required edge "SubscriptionOrder.group"`)}
	}
	return nil
}

func (_c *SubscriptionOrderCreate) sqlSave(ctx context.Context) (*SubscriptionOrder, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	_node.ID = int64(id)
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *SubscriptionOrderCreate) createSpec() (*SubscriptionOrder, *sqlgraph.CreateSpec) {
	var (
		_node = &SubscriptionOrder{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(subscriptionorder.Table, sqlgraph.NewFieldSpec(subscriptionorder.FieldID, field.TypeInt64))
	)
	_spec.OnConflict = _c.conflict
	if value, ok := _c.mutation.CreatedAt(); ok {
		_spec.SetField(subscriptionorder.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	if value, ok := _c.mutation.UpdatedAt(); ok {
		_spec.SetField(subscriptionorder.FieldUpdatedAt, field.TypeTime, value)
		_node.UpdatedAt = value
	}
	if value, ok := _c.mutation.OrderNo(); ok {
		_spec.SetField(subscriptionorder.FieldOrderNo, field.TypeString, value)
		_node.OrderNo = value
	}
	if value, ok := _c.mutation.PaymentProvider(); ok {
		_spec.SetField(subscriptionorder.FieldPaymentProvider, field.TypeString, value)
		_node.PaymentProvider = value
	}
	if value, ok := _c.mutation.PaymentURL(); ok {
		_spec.SetField(subscriptionorder.FieldPaymentURL, field.TypeString, value)
		_node.PaymentURL = &value
	}
	if value, ok := _c.mutation.PaymentQrcode(); ok {
		_spec.SetField(subscriptionorder.FieldPaymentQrcode, field.TypeString, value)
		_node.PaymentQrcode = &value
	}
	if value, ok := _c.mutation.PaymentOpenOrderID(); ok {
		_spec.SetField(subscriptionorder.FieldPaymentOpenOrderID, field.TypeString, value)
		_node.PaymentOpenOrderID = &value
	}
	if value, ok := _c.mutation.PaymentTransactionID(); ok {
		_spec.SetField(subscriptionorder.FieldPaymentTransactionID, field.TypeString, value)
		_node.PaymentTransactionID = &value
	}
	if value, ok := _c.mutation.PaymentPlugin(); ok {
		_spec.SetField(subscriptionorder.FieldPaymentPlugin, field.TypeString, value)
		_node.PaymentPlugin = &value
	}
	if value, ok := _c.mutation.Status(); ok {
		_spec.SetField(subscriptionorder.FieldStatus, field.TypeString, value)
		_node.Status = value
	}
	if value, ok := _c.mutation.Amount(); ok {
		_spec.SetField(subscriptionorder.FieldAmount, field.TypeFloat64, value)
		_node.Amount = value
	}
	if value, ok := _c.mutation.Currency(); ok {
		_spec.SetField(subscriptionorder.FieldCurrency, field.TypeString, value)
		_node.Currency = value
	}
	if value, ok := _c.mutation.ValidityDays(); ok {
		_spec.SetField(subscriptionorder.FieldValidityDays, field.TypeInt, value)
		_node.ValidityDays = value
	}
	if value, ok := _c.mutation.PaidAt(); ok {
		_spec.SetField(subscriptionorder.FieldPaidAt, field.TypeTime, value)
		_node.PaidAt = &value
	}
	if value, ok := _c.mutation.CanceledAt(); ok {
		_spec.SetField(subscriptionorder.FieldCanceledAt, field.TypeTime, value)
		_node.CanceledAt = &value
	}
	if value, ok := _c.mutation.Notes(); ok {
		_spec.SetField(subscriptionorder.FieldNotes, field.TypeString, value)
		_node.Notes = &value
	}
	if nodes := _c.mutation.UserIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   subscriptionorder.UserTable,
			Columns: []string{subscriptionorder.UserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.UserID = nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := _c.mutation.GroupIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   subscriptionorder.GroupTable,
			Columns: []string{subscriptionorder.GroupColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(group.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.GroupID = nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := _c.mutation.SubscriptionIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   subscriptionorder.SubscriptionTable,
			Columns: []string{subscriptionorder.SubscriptionColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(usersubscription.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.SubscriptionID = &nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.SubscriptionOrder.Create().
//		SetCreatedAt(v).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.SubscriptionOrderUpsert) {
//			SetCreatedAt(v+v).
//		}).
//		Exec(ctx)
func (_c *SubscriptionOrderCreate) OnConflict(opts ...sql.ConflictOption) *SubscriptionOrderUpsertOne {
	_c.conflict = opts
	return &SubscriptionOrderUpsertOne{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.SubscriptionOrder.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *SubscriptionOrderCreate) OnConflictColumns(columns ...string) *SubscriptionOrderUpsertOne {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &SubscriptionOrderUpsertOne{
		create: _c,
	}
}

type (
	// SubscriptionOrderUpsertOne is the builder for "upsert"-ing
	//  one SubscriptionOrder node.
	SubscriptionOrderUpsertOne struct {
		create *SubscriptionOrderCreate
	}

	// SubscriptionOrderUpsert is the "OnConflict" setter.
	SubscriptionOrderUpsert struct {
		*sql.UpdateSet
	}
)

// SetUpdatedAt sets the "updated_at" field.
func (u *SubscriptionOrderUpsert) SetUpdatedAt(v time.Time) *SubscriptionOrderUpsert {
	u.Set(subscriptionorder.FieldUpdatedAt, v)
	return u
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *SubscriptionOrderUpsert) UpdateUpdatedAt() *SubscriptionOrderUpsert {
	u.SetExcluded(subscriptionorder.FieldUpdatedAt)
	return u
}

// SetOrderNo sets the "order_no" field.
func (u *SubscriptionOrderUpsert) SetOrderNo(v string) *SubscriptionOrderUpsert {
	u.Set(subscriptionorder.FieldOrderNo, v)
	return u
}

// UpdateOrderNo sets the "order_no" field to the value that was provided on create.
func (u *SubscriptionOrderUpsert) UpdateOrderNo() *SubscriptionOrderUpsert {
	u.SetExcluded(subscriptionorder.FieldOrderNo)
	return u
}

// SetUserID sets the "user_id" field.
func (u *SubscriptionOrderUpsert) SetUserID(v int64) *SubscriptionOrderUpsert {
	u.Set(subscriptionorder.FieldUserID, v)
	return u
}

// UpdateUserID sets the "user_id" field to the value that was provided on create.
func (u *SubscriptionOrderUpsert) UpdateUserID() *SubscriptionOrderUpsert {
	u.SetExcluded(subscriptionorder.FieldUserID)
	return u
}

// SetGroupID sets the "group_id" field.
func (u *SubscriptionOrderUpsert) SetGroupID(v int64) *SubscriptionOrderUpsert {
	u.Set(subscriptionorder.FieldGroupID, v)
	return u
}

// UpdateGroupID sets the "group_id" field to the value that was provided on create.
func (u *SubscriptionOrderUpsert) UpdateGroupID() *SubscriptionOrderUpsert {
	u.SetExcluded(subscriptionorder.FieldGroupID)
	return u
}

// SetSubscriptionID sets the "subscription_id" field.
func (u *SubscriptionOrderUpsert) SetSubscriptionID(v int64) *SubscriptionOrderUpsert {
	u.Set(subscriptionorder.FieldSubscriptionID, v)
	return u
}

// UpdateSubscriptionID sets the "subscription_id" field to the value that was provided on create.
func (u *SubscriptionOrderUpsert) UpdateSubscriptionID() *SubscriptionOrderUpsert {
	u.SetExcluded(subscriptionorder.FieldSubscriptionID)
	return u
}

// ClearSubscriptionID clears the value of the "subscription_id" field.
func (u *SubscriptionOrderUpsert) ClearSubscriptionID() *SubscriptionOrderUpsert {
	u.SetNull(subscriptionorder.FieldSubscriptionID)
	return u
}

// SetPaymentProvider sets the "payment_provider" field.
func (u *SubscriptionOrderUpsert) SetPaymentProvider(v string) *SubscriptionOrderUpsert {
	u.Set(subscriptionorder.FieldPaymentProvider, v)
	return u
}

// UpdatePaymentProvider sets the "payment_provider" field to the value that was provided on create.
func (u *SubscriptionOrderUpsert) UpdatePaymentProvider() *SubscriptionOrderUpsert {
	u.SetExcluded(subscriptionorder.FieldPaymentProvider)
	return u
}

// SetPaymentURL sets the "payment_url" field.
func (u *SubscriptionOrderUpsert) SetPaymentURL(v string) *SubscriptionOrderUpsert {
	u.Set(subscriptionorder.FieldPaymentURL, v)
	return u
}

// UpdatePaymentURL sets the "payment_url" field to the value that was provided on create.
func (u *SubscriptionOrderUpsert) UpdatePaymentURL() *SubscriptionOrderUpsert {
	u.SetExcluded(subscriptionorder.FieldPaymentURL)
	return u
}

// ClearPaymentURL clears the value of the "payment_url" field.
func (u *SubscriptionOrderUpsert) ClearPaymentURL() *SubscriptionOrderUpsert {
	u.SetNull(subscriptionorder.FieldPaymentURL)
	return u
}

// SetPaymentQrcode sets the "payment_qrcode" field.
func (u *SubscriptionOrderUpsert) SetPaymentQrcode(v string) *SubscriptionOrderUpsert {
	u.Set(subscriptionorder.FieldPaymentQrcode, v)
	return u
}

// UpdatePaymentQrcode sets the "payment_qrcode" field to the value that was provided on create.
func (u *SubscriptionOrderUpsert) UpdatePaymentQrcode() *SubscriptionOrderUpsert {
	u.SetExcluded(subscriptionorder.FieldPaymentQrcode)
	return u
}

// ClearPaymentQrcode clears the value of the "payment_qrcode" field.
func (u *SubscriptionOrderUpsert) ClearPaymentQrcode() *SubscriptionOrderUpsert {
	u.SetNull(subscriptionorder.FieldPaymentQrcode)
	return u
}

// SetPaymentOpenOrderID sets the "payment_open_order_id" field.
func (u *SubscriptionOrderUpsert) SetPaymentOpenOrderID(v string) *SubscriptionOrderUpsert {
	u.Set(subscriptionorder.FieldPaymentOpenOrderID, v)
	return u
}

// UpdatePaymentOpenOrderID sets the "payment_open_order_id" field to the value that was provided on create.
func (u *SubscriptionOrderUpsert) UpdatePaymentOpenOrderID() *SubscriptionOrderUpsert {
	u.SetExcluded(subscriptionorder.FieldPaymentOpenOrderID)
	return u
}

// ClearPaymentOpenOrderID clears the value of the "payment_open_order_id" field.
func (u *SubscriptionOrderUpsert) ClearPaymentOpenOrderID() *SubscriptionOrderUpsert {
	u.SetNull(subscriptionorder.FieldPaymentOpenOrderID)
	return u
}

// SetPaymentTransactionID sets the "payment_transaction_id" field.
func (u *SubscriptionOrderUpsert) SetPaymentTransactionID(v string) *SubscriptionOrderUpsert {
	u.Set(subscriptionorder.FieldPaymentTransactionID, v)
	return u
}

// UpdatePaymentTransactionID sets the "payment_transaction_id" field to the value that was provided on create.
func (u *SubscriptionOrderUpsert) UpdatePaymentTransactionID() *SubscriptionOrderUpsert {
	u.SetExcluded(subscriptionorder.FieldPaymentTransactionID)
	return u
}

// ClearPaymentTransactionID clears the value of the "payment_transaction_id" field.
func (u *SubscriptionOrderUpsert) ClearPaymentTransactionID() *SubscriptionOrderUpsert {
	u.SetNull(subscriptionorder.FieldPaymentTransactionID)
	return u
}

// SetPaymentPlugin sets the "payment_plugin" field.
func (u *SubscriptionOrderUpsert) SetPaymentPlugin(v string) *SubscriptionOrderUpsert {
	u.Set(subscriptionorder.FieldPaymentPlugin, v)
	return u
}

// UpdatePaymentPlugin sets the "payment_plugin" field to the value that was provided on create.
func (u *SubscriptionOrderUpsert) UpdatePaymentPlugin() *SubscriptionOrderUpsert {
	u.SetExcluded(subscriptionorder.FieldPaymentPlugin)
	return u
}

// ClearPaymentPlugin clears the value of the "payment_plugin" field.
func (u *SubscriptionOrderUpsert) ClearPaymentPlugin() *SubscriptionOrderUpsert {
	u.SetNull(subscriptionorder.FieldPaymentPlugin)
	return u
}

// SetStatus sets the "status" field.
func (u *SubscriptionOrderUpsert) SetStatus(v string) *SubscriptionOrderUpsert {
	u.Set(subscriptionorder.FieldStatus, v)
	return u
}

// UpdateStatus sets the "status" field to the value that was provided on create.
func (u *SubscriptionOrderUpsert) UpdateStatus() *SubscriptionOrderUpsert {
	u.SetExcluded(subscriptionorder.FieldStatus)
	return u
}

// SetAmount sets the "amount" field.
func (u *SubscriptionOrderUpsert) SetAmount(v float64) *SubscriptionOrderUpsert {
	u.Set(subscriptionorder.FieldAmount, v)
	return u
}

// UpdateAmount sets the "amount" field to the value that was provided on create.
func (u *SubscriptionOrderUpsert) UpdateAmount() *SubscriptionOrderUpsert {
	u.SetExcluded(subscriptionorder.FieldAmount)
	return u
}

// AddAmount adds v to the "amount" field.
func (u *SubscriptionOrderUpsert) AddAmount(v float64) *SubscriptionOrderUpsert {
	u.Add(subscriptionorder.FieldAmount, v)
	return u
}

// SetCurrency sets the "currency" field.
func (u *SubscriptionOrderUpsert) SetCurrency(v string) *SubscriptionOrderUpsert {
	u.Set(subscriptionorder.FieldCurrency, v)
	return u
}

// UpdateCurrency sets the "currency" field to the value that was provided on create.
func (u *SubscriptionOrderUpsert) UpdateCurrency() *SubscriptionOrderUpsert {
	u.SetExcluded(subscriptionorder.FieldCurrency)
	return u
}

// SetValidityDays sets the "validity_days" field.
func (u *SubscriptionOrderUpsert) SetValidityDays(v int) *SubscriptionOrderUpsert {
	u.Set(subscriptionorder.FieldValidityDays, v)
	return u
}

// UpdateValidityDays sets the "validity_days" field to the value that was provided on create.
func (u *SubscriptionOrderUpsert) UpdateValidityDays() *SubscriptionOrderUpsert {
	u.SetExcluded(subscriptionorder.FieldValidityDays)
	return u
}

// AddValidityDays adds v to the "validity_days" field.
func (u *SubscriptionOrderUpsert) AddValidityDays(v int) *SubscriptionOrderUpsert {
	u.Add(subscriptionorder.FieldValidityDays, v)
	return u
}

// SetPaidAt sets the "paid_at" field.
func (u *SubscriptionOrderUpsert) SetPaidAt(v time.Time) *SubscriptionOrderUpsert {
	u.Set(subscriptionorder.FieldPaidAt, v)
	return u
}

// UpdatePaidAt sets the "paid_at" field to the value that was provided on create.
func (u *SubscriptionOrderUpsert) UpdatePaidAt() *SubscriptionOrderUpsert {
	u.SetExcluded(subscriptionorder.FieldPaidAt)
	return u
}

// ClearPaidAt clears the value of the "paid_at" field.
func (u *SubscriptionOrderUpsert) ClearPaidAt() *SubscriptionOrderUpsert {
	u.SetNull(subscriptionorder.FieldPaidAt)
	return u
}

// SetCanceledAt sets the "canceled_at" field.
func (u *SubscriptionOrderUpsert) SetCanceledAt(v time.Time) *SubscriptionOrderUpsert {
	u.Set(subscriptionorder.FieldCanceledAt, v)
	return u
}

// UpdateCanceledAt sets the "canceled_at" field to the value that was provided on create.
func (u *SubscriptionOrderUpsert) UpdateCanceledAt() *SubscriptionOrderUpsert {
	u.SetExcluded(subscriptionorder.FieldCanceledAt)
	return u
}

// ClearCanceledAt clears the value of the "canceled_at" field.
func (u *SubscriptionOrderUpsert) ClearCanceledAt() *SubscriptionOrderUpsert {
	u.SetNull(subscriptionorder.FieldCanceledAt)
	return u
}

// SetNotes sets the "notes" field.
func (u *SubscriptionOrderUpsert) SetNotes(v string) *SubscriptionOrderUpsert {
	u.Set(subscriptionorder.FieldNotes, v)
	return u
}

// UpdateNotes sets the "notes" field to the value that was provided on create.
func (u *SubscriptionOrderUpsert) UpdateNotes() *SubscriptionOrderUpsert {
	u.SetExcluded(subscriptionorder.FieldNotes)
	return u
}

// ClearNotes clears the value of the "notes" field.
func (u *SubscriptionOrderUpsert) ClearNotes() *SubscriptionOrderUpsert {
	u.SetNull(subscriptionorder.FieldNotes)
	return u
}

// UpdateNewValues updates the mutable fields using the new values that were set on create.
// Using this option is equivalent to using:
//
//	client.SubscriptionOrder.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//		).
//		Exec(ctx)
func (u *SubscriptionOrderUpsertOne) UpdateNewValues() *SubscriptionOrderUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		if _, exists := u.create.mutation.CreatedAt(); exists {
			s.SetIgnore(subscriptionorder.FieldCreatedAt)
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.SubscriptionOrder.Create().
//	    OnConflict(sql.ResolveWithIgnore()).
//	    Exec(ctx)
func (u *SubscriptionOrderUpsertOne) Ignore() *SubscriptionOrderUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *SubscriptionOrderUpsertOne) DoNothing() *SubscriptionOrderUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the SubscriptionOrderCreate.OnConflict
// documentation for more info.
func (u *SubscriptionOrderUpsertOne) Update(set func(*SubscriptionOrderUpsert)) *SubscriptionOrderUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&SubscriptionOrderUpsert{UpdateSet: update})
	}))
	return u
}

// SetUpdatedAt sets the "updated_at" field.
func (u *SubscriptionOrderUpsertOne) SetUpdatedAt(v time.Time) *SubscriptionOrderUpsertOne {
	return u.Update(func(s *SubscriptionOrderUpsert) {
		s.SetUpdatedAt(v)
	})
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *SubscriptionOrderUpsertOne) UpdateUpdatedAt() *SubscriptionOrderUpsertOne {
	return u.Update(func(s *SubscriptionOrderUpsert) {
		s.UpdateUpdatedAt()
	})
}

// SetOrderNo sets the "order_no" field.
func (u *SubscriptionOrderUpsertOne) SetOrderNo(v string) *SubscriptionOrderUpsertOne {
	return u.Update(func(s *SubscriptionOrderUpsert) {
		s.SetOrderNo(v)
	})
}

// UpdateOrderNo sets the "order_no" field to the value that was provided on create.
func (u *SubscriptionOrderUpsertOne) UpdateOrderNo() *SubscriptionOrderUpsertOne {
	return u.Update(func(s *SubscriptionOrderUpsert) {
		s.UpdateOrderNo()
	})
}

// SetUserID sets the "user_id" field.
func (u *SubscriptionOrderUpsertOne) SetUserID(v int64) *SubscriptionOrderUpsertOne {
	return u.Update(func(s *SubscriptionOrderUpsert) {
		s.SetUserID(v)
	})
}

// UpdateUserID sets the "user_id" field to the value that was provided on create.
func (u *SubscriptionOrderUpsertOne) UpdateUserID() *SubscriptionOrderUpsertOne {
	return u.Update(func(s *SubscriptionOrderUpsert) {
		s.UpdateUserID()
	})
}

// SetGroupID sets the "group_id" field.
func (u *SubscriptionOrderUpsertOne) SetGroupID(v int64) *SubscriptionOrderUpsertOne {
	return u.Update(func(s *SubscriptionOrderUpsert) {
		s.SetGroupID(v)
	})
}

// UpdateGroupID sets the "group_id" field to the value that was provided on create.
func (u *SubscriptionOrderUpsertOne) UpdateGroupID() *SubscriptionOrderUpsertOne {
	return u.Update(func(s *SubscriptionOrderUpsert) {
		s.UpdateGroupID()
	})
}

// SetSubscriptionID sets the "subscription_id" field.
func (u *SubscriptionOrderUpsertOne) SetSubscriptionID(v int64) *SubscriptionOrderUpsertOne {
	return u.Update(func(s *SubscriptionOrderUpsert) {
		s.SetSubscriptionID(v)
	})
}

// UpdateSubscriptionID sets the "subscription_id" field to the value that was provided on create.
func (u *SubscriptionOrderUpsertOne) UpdateSubscriptionID() *SubscriptionOrderUpsertOne {
	return u.Update(func(s *SubscriptionOrderUpsert) {
		s.UpdateSubscriptionID()
	})
}

// ClearSubscriptionID clears the value of the "subscription_id" field.
func (u *SubscriptionOrderUpsertOne) ClearSubscriptionID() *SubscriptionOrderUpsertOne {
	return u.Update(func(s *SubscriptionOrderUpsert) {
		s.ClearSubscriptionID()
	})
}

// SetPaymentProvider sets the "payment_provider" field.
func (u *SubscriptionOrderUpsertOne) SetPaymentProvider(v string) *SubscriptionOrderUpsertOne {
	return u.Update(func(s *SubscriptionOrderUpsert) {
		s.SetPaymentProvider(v)
	})
}

// UpdatePaymentProvider sets the "payment_provider" field to the value that was provided on create.
func (u *SubscriptionOrderUpsertOne) UpdatePaymentProvider() *SubscriptionOrderUpsertOne {
	return u.Update(func(s *SubscriptionOrderUpsert) {
		s.UpdatePaymentProvider()
	})
}

// SetPaymentURL sets the "payment_url" field.
func (u *SubscriptionOrderUpsertOne) SetPaymentURL(v string) *SubscriptionOrderUpsertOne {
	return u.Update(func(s *SubscriptionOrderUpsert) {
		s.SetPaymentURL(v)
	})
}

// UpdatePaymentURL sets the "payment_url" field to the value that was provided on create.
func (u *SubscriptionOrderUpsertOne) UpdatePaymentURL() *SubscriptionOrderUpsertOne {
	return u.Update(func(s *SubscriptionOrderUpsert) {
		s.UpdatePaymentURL()
	})
}

// ClearPaymentURL clears the value of the "payment_url" field.
func (u *SubscriptionOrderUpsertOne) ClearPaymentURL() *SubscriptionOrderUpsertOne {
	return u.Update(func(s *SubscriptionOrderUpsert) {
		s.ClearPaymentURL()
	})
}

// SetPaymentQrcode sets the "payment_qrcode" field.
func (u *SubscriptionOrderUpsertOne) SetPaymentQrcode(v string) *SubscriptionOrderUpsertOne {
	return u.Update(func(s *SubscriptionOrderUpsert) {
		s.SetPaymentQrcode(v)
	})
}

// UpdatePaymentQrcode sets the "payment_qrcode" field to the value that was provided on create.
func (u *SubscriptionOrderUpsertOne) UpdatePaymentQrcode() *SubscriptionOrderUpsertOne {
	return u.Update(func(s *SubscriptionOrderUpsert) {
		s.UpdatePaymentQrcode()
	})
}

// ClearPaymentQrcode clears the value of the "payment_qrcode" field.
func (u *SubscriptionOrderUpsertOne) ClearPaymentQrcode() *SubscriptionOrderUpsertOne {
	return u.Update(func(s *SubscriptionOrderUpsert) {
		s.ClearPaymentQrcode()
	})
}

// SetPaymentOpenOrderID sets the "payment_open_order_id" field.
func (u *SubscriptionOrderUpsertOne) SetPaymentOpenOrderID(v string) *SubscriptionOrderUpsertOne {
	return u.Update(func(s *SubscriptionOrderUpsert) {
		s.SetPaymentOpenOrderID(v)
	})
}

// UpdatePaymentOpenOrderID sets the "payment_open_order_id" field to the value that was provided on create.
func (u *SubscriptionOrderUpsertOne) UpdatePaymentOpenOrderID() *SubscriptionOrderUpsertOne {
	return u.Update(func(s *SubscriptionOrderUpsert) {
		s.UpdatePaymentOpenOrderID()
	})
}

// ClearPaymentOpenOrderID clears the value of the "payment_open_order_id" field.
func (u *SubscriptionOrderUpsertOne) ClearPaymentOpenOrderID() *SubscriptionOrderUpsertOne {
	return u.Update(func(s *SubscriptionOrderUpsert) {
		s.ClearPaymentOpenOrderID()
	})
}

// SetPaymentTransactionID sets the "payment_transaction_id" field.
func (u *SubscriptionOrderUpsertOne) SetPaymentTransactionID(v string) *SubscriptionOrderUpsertOne {
	return u.Update(func(s *SubscriptionOrderUpsert) {
		s.SetPaymentTransactionID(v)
	})
}

// UpdatePaymentTransactionID sets the "payment_transaction_id" field to the value that was provided on create.
func (u *SubscriptionOrderUpsertOne) UpdatePaymentTransactionID() *SubscriptionOrderUpsertOne {
	return u.Update(func(s *SubscriptionOrderUpsert) {
		s.UpdatePaymentTransactionID()
	})
}

// ClearPaymentTransactionID clears the value of the "payment_transaction_id" field.
func (u *SubscriptionOrderUpsertOne) ClearPaymentTransactionID() *SubscriptionOrderUpsertOne {
	return u.Update(func(s *SubscriptionOrderUpsert) {
		s.ClearPaymentTransactionID()
	})
}

// SetPaymentPlugin sets the "payment_plugin" field.
func (u *SubscriptionOrderUpsertOne) SetPaymentPlugin(v string) *SubscriptionOrderUpsertOne {
	return u.Update(func(s *SubscriptionOrderUpsert) {
		s.SetPaymentPlugin(v)
	})
}

// UpdatePaymentPlugin sets the "payment_plugin" field to the value that was provided on create.
func (u *SubscriptionOrderUpsertOne) UpdatePaymentPlugin() *SubscriptionOrderUpsertOne {
	return u.Update(func(s *SubscriptionOrderUpsert) {
		s.UpdatePaymentPlugin()
	})
}

// ClearPaymentPlugin clears the value of the "payment_plugin" field.
func (u *SubscriptionOrderUpsertOne) ClearPaymentPlugin() *SubscriptionOrderUpsertOne {
	return u.Update(func(s *SubscriptionOrderUpsert) {
		s.ClearPaymentPlugin()
	})
}

// SetStatus sets the "status" field.
func (u *SubscriptionOrderUpsertOne) SetStatus(v string) *SubscriptionOrderUpsertOne {
	return u.Update(func(s *SubscriptionOrderUpsert) {
		s.SetStatus(v)
	})
}

// UpdateStatus sets the "status" field to the value that was provided on create.
func (u *SubscriptionOrderUpsertOne) UpdateStatus() *SubscriptionOrderUpsertOne {
	return u.Update(func(s *SubscriptionOrderUpsert) {
		s.UpdateStatus()
	})
}

// SetAmount sets the "amount" field.
func (u *SubscriptionOrderUpsertOne) SetAmount(v float64) *SubscriptionOrderUpsertOne {
	return u.Update(func(s *SubscriptionOrderUpsert) {
		s.SetAmount(v)
	})
}

// AddAmount adds v to the "amount" field.
func (u *SubscriptionOrderUpsertOne) AddAmount(v float64) *SubscriptionOrderUpsertOne {
	return u.Update(func(s *SubscriptionOrderUpsert) {
		s.AddAmount(v)
	})
}

// UpdateAmount sets the "amount" field to the value that was provided on create.
func (u *SubscriptionOrderUpsertOne) UpdateAmount() *SubscriptionOrderUpsertOne {
	return u.Update(func(s *SubscriptionOrderUpsert) {
		s.UpdateAmount()
	})
}

// SetCurrency sets the "currency" field.
func (u *SubscriptionOrderUpsertOne) SetCurrency(v string) *SubscriptionOrderUpsertOne {
	return u.Update(func(s *SubscriptionOrderUpsert) {
		s.SetCurrency(v)
	})
}

// UpdateCurrency sets the "currency" field to the value that was provided on create.
func (u *SubscriptionOrderUpsertOne) UpdateCurrency() *SubscriptionOrderUpsertOne {
	return u.Update(func(s *SubscriptionOrderUpsert) {
		s.UpdateCurrency()
	})
}

// SetValidityDays sets the "validity_days" field.
func (u *SubscriptionOrderUpsertOne) SetValidityDays(v int) *SubscriptionOrderUpsertOne {
	return u.Update(func(s *SubscriptionOrderUpsert) {
		s.SetValidityDays(v)
	})
}

// AddValidityDays adds v to the "validity_days" field.
func (u *SubscriptionOrderUpsertOne) AddValidityDays(v int) *SubscriptionOrderUpsertOne {
	return u.Update(func(s *SubscriptionOrderUpsert) {
		s.AddValidityDays(v)
	})
}

// UpdateValidityDays sets the "validity_days" field to the value that was provided on create.
func (u *SubscriptionOrderUpsertOne) UpdateValidityDays() *SubscriptionOrderUpsertOne {
	return u.Update(func(s *SubscriptionOrderUpsert) {
		s.UpdateValidityDays()
	})
}

// SetPaidAt sets the "paid_at" field.
func (u *SubscriptionOrderUpsertOne) SetPaidAt(v time.Time) *SubscriptionOrderUpsertOne {
	return u.Update(func(s *SubscriptionOrderUpsert) {
		s.SetPaidAt(v)
	})
}

// UpdatePaidAt sets the "paid_at" field to the value that was provided on create.
func (u *SubscriptionOrderUpsertOne) UpdatePaidAt() *SubscriptionOrderUpsertOne {
	return u.Update(func(s *SubscriptionOrderUpsert) {
		s.UpdatePaidAt()
	})
}

// ClearPaidAt clears the value of the "paid_at" field.
func (u *SubscriptionOrderUpsertOne) ClearPaidAt() *SubscriptionOrderUpsertOne {
	return u.Update(func(s *SubscriptionOrderUpsert) {
		s.ClearPaidAt()
	})
}

// SetCanceledAt sets the "canceled_at" field.
func (u *SubscriptionOrderUpsertOne) SetCanceledAt(v time.Time) *SubscriptionOrderUpsertOne {
	return u.Update(func(s *SubscriptionOrderUpsert) {
		s.SetCanceledAt(v)
	})
}

// UpdateCanceledAt sets the "canceled_at" field to the value that was provided on create.
func (u *SubscriptionOrderUpsertOne) UpdateCanceledAt() *SubscriptionOrderUpsertOne {
	return u.Update(func(s *SubscriptionOrderUpsert) {
		s.UpdateCanceledAt()
	})
}

// ClearCanceledAt clears the value of the "canceled_at" field.
func (u *SubscriptionOrderUpsertOne) ClearCanceledAt() *SubscriptionOrderUpsertOne {
	return u.Update(func(s *SubscriptionOrderUpsert) {
		s.ClearCanceledAt()
	})
}

// SetNotes sets the "notes" field.
func (u *SubscriptionOrderUpsertOne) SetNotes(v string) *SubscriptionOrderUpsertOne {
	return u.Update(func(s *SubscriptionOrderUpsert) {
		s.SetNotes(v)
	})
}

// UpdateNotes sets the "notes" field to the value that was provided on create.
func (u *SubscriptionOrderUpsertOne) UpdateNotes() *SubscriptionOrderUpsertOne {
	return u.Update(func(s *SubscriptionOrderUpsert) {
		s.UpdateNotes()
	})
}

// ClearNotes clears the value of the "notes" field.
func (u *SubscriptionOrderUpsertOne) ClearNotes() *SubscriptionOrderUpsertOne {
	return u.Update(func(s *SubscriptionOrderUpsert) {
		s.ClearNotes()
	})
}

// Exec executes the query.
func (u *SubscriptionOrderUpsertOne) Exec(ctx context.Context) error {
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for SubscriptionOrderCreate.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *SubscriptionOrderUpsertOne) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}

// Exec executes the UPSERT query and returns the inserted/updated ID.
func (u *SubscriptionOrderUpsertOne) ID(ctx context.Context) (id int64, err error) {
	node, err := u.create.Save(ctx)
	if err != nil {
		return id, err
	}
	return node.ID, nil
}

// IDX is like ID, but panics if an error occurs.
func (u *SubscriptionOrderUpsertOne) IDX(ctx context.Context) int64 {
	id, err := u.ID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// SubscriptionOrderCreateBulk is the builder for creating many SubscriptionOrder entities in bulk.
type SubscriptionOrderCreateBulk struct {
	config
	err      error
	builders []*SubscriptionOrderCreate
	conflict []sql.ConflictOption
}

// Save creates the SubscriptionOrder entities in the database.
func (_c *SubscriptionOrderCreateBulk) Save(ctx context.Context) ([]*SubscriptionOrder, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*SubscriptionOrder, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*SubscriptionOrderMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					spec.OnConflict = _c.conflict
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int64(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *SubscriptionOrderCreateBulk) SaveX(ctx context.Context) []*SubscriptionOrder {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *SubscriptionOrderCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *SubscriptionOrderCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.SubscriptionOrder.CreateBulk(builders...).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.SubscriptionOrderUpsert) {
//			SetCreatedAt(v+v).
//		}).
//		Exec(ctx)
func (_c *SubscriptionOrderCreateBulk) OnConflict(opts ...sql.ConflictOption) *SubscriptionOrderUpsertBulk {
	_c.conflict = opts
	return &SubscriptionOrderUpsertBulk{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.SubscriptionOrder.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *SubscriptionOrderCreateBulk) OnConflictColumns(columns ...string) *SubscriptionOrderUpsertBulk {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &SubscriptionOrderUpsertBulk{
		create: _c,
	}
}

// SubscriptionOrderUpsertBulk is the builder for "upsert"-ing
// a bulk of SubscriptionOrder nodes.
type SubscriptionOrderUpsertBulk struct {
	create *SubscriptionOrderCreateBulk
}

// UpdateNewValues updates the mutable fields using the new values that
// were set on create. Using this option is equivalent to using:
//
//	client.SubscriptionOrder.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//		).
//		Exec(ctx)
func (u *SubscriptionOrderUpsertBulk) UpdateNewValues() *SubscriptionOrderUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		for _, b := range u.create.builders {
			if _, exists := b.mutation.CreatedAt(); exists {
				s.SetIgnore(subscriptionorder.FieldCreatedAt)
			}
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.SubscriptionOrder.Create().
//		OnConflict(sql.ResolveWithIgnore()).
//		Exec(ctx)
func (u *SubscriptionOrderUpsertBulk) Ignore() *SubscriptionOrderUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *SubscriptionOrderUpsertBulk) DoNothing() *SubscriptionOrderUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the SubscriptionOrderCreateBulk.OnConflict
// documentation for more info.
func (u *SubscriptionOrderUpsertBulk) Update(set func(*SubscriptionOrderUpsert)) *SubscriptionOrderUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&SubscriptionOrderUpsert{UpdateSet: update})
	}))
	return u
}

// SetUpdatedAt sets the "updated_at" field.
func (u *SubscriptionOrderUpsertBulk) SetUpdatedAt(v time.Time) *SubscriptionOrderUpsertBulk {
	return u.Update(func(s *SubscriptionOrderUpsert) {
		s.SetUpdatedAt(v)
	})
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *SubscriptionOrderUpsertBulk) UpdateUpdatedAt() *SubscriptionOrderUpsertBulk {
	return u.Update(func(s *SubscriptionOrderUpsert) {
		s.UpdateUpdatedAt()
	})
}

// SetOrderNo sets the "order_no" field.
func (u *SubscriptionOrderUpsertBulk) SetOrderNo(v string) *SubscriptionOrderUpsertBulk {
	return u.Update(func(s *SubscriptionOrderUpsert) {
		s.SetOrderNo(v)
	})
}

// UpdateOrderNo sets the "order_no" field to the value that was provided on create.
func (u *SubscriptionOrderUpsertBulk) UpdateOrderNo() *SubscriptionOrderUpsertBulk {
	return u.Update(func(s *SubscriptionOrderUpsert) {
		s.UpdateOrderNo()
	})
}

// SetUserID sets the "user_id" field.
func (u *SubscriptionOrderUpsertBulk) SetUserID(v int64) *SubscriptionOrderUpsertBulk {
	return u.Update(func(s *SubscriptionOrderUpsert) {
		s.SetUserID(v)
	})
}

// UpdateUserID sets the "user_id" field to the value that was provided on create.
func (u *SubscriptionOrderUpsertBulk) UpdateUserID() *SubscriptionOrderUpsertBulk {
	return u.Update(func(s *SubscriptionOrderUpsert) {
		s.UpdateUserID()
	})
}

// SetGroupID sets the "group_id" field.
func (u *SubscriptionOrderUpsertBulk) SetGroupID(v int64) *SubscriptionOrderUpsertBulk {
	return u.Update(func(s *SubscriptionOrderUpsert) {
		s.SetGroupID(v)
	})
}

// UpdateGroupID sets the "group_id" field to the value that was provided on create.
func (u *SubscriptionOrderUpsertBulk) UpdateGroupID() *SubscriptionOrderUpsertBulk {
	return u.Update(func(s *SubscriptionOrderUpsert) {
		s.UpdateGroupID()
	})
}

// SetSubscriptionID sets the "subscription_id" field.
func (u *SubscriptionOrderUpsertBulk) SetSubscriptionID(v int64) *SubscriptionOrderUpsertBulk {
	return u.Update(func(s *SubscriptionOrderUpsert) {
		s.SetSubscriptionID(v)
	})
}

// UpdateSubscriptionID sets the "subscription_id" field to the value that was provided on create.
func (u *SubscriptionOrderUpsertBulk) UpdateSubscriptionID() *SubscriptionOrderUpsertBulk {
	return u.Update(func(s *SubscriptionOrderUpsert) {
		s.UpdateSubscriptionID()
	})
}

// ClearSubscriptionID clears the value of the "subscription_id" field.
func (u *SubscriptionOrderUpsertBulk) ClearSubscriptionID() *SubscriptionOrderUpsertBulk {
	return u.Update(func(s *SubscriptionOrderUpsert) {
		s.ClearSubscriptionID()
	})
}

// SetPaymentProvider sets the "payment_provider" field.
func (u *SubscriptionOrderUpsertBulk) SetPaymentProvider(v string) *SubscriptionOrderUpsertBulk {
	return u.Update(func(s *SubscriptionOrderUpsert) {
		s.SetPaymentProvider(v)
	})
}

// UpdatePaymentProvider sets the "payment_provider" field to the value that was provided on create.
func (u *SubscriptionOrderUpsertBulk) UpdatePaymentProvider() *SubscriptionOrderUpsertBulk {
	return u.Update(func(s *SubscriptionOrderUpsert) {
		s.UpdatePaymentProvider()
	})
}

// SetPaymentURL sets the "payment_url" field.
func (u *SubscriptionOrderUpsertBulk) SetPaymentURL(v string) *SubscriptionOrderUpsertBulk {
	return u.Update(func(s *SubscriptionOrderUpsert) {
		s.SetPaymentURL(v)
	})
}

// UpdatePaymentURL sets the "payment_url" field to the value that was provided on create.
func (u *SubscriptionOrderUpsertBulk) UpdatePaymentURL() *SubscriptionOrderUpsertBulk {
	return u.Update(func(s *SubscriptionOrderUpsert) {
		s.UpdatePaymentURL()
	})
}

// ClearPaymentURL clears the value of the "payment_url" field.
func (u *SubscriptionOrderUpsertBulk) ClearPaymentURL() *SubscriptionOrderUpsertBulk {
	return u.Update(func(s *SubscriptionOrderUpsert) {
		s.ClearPaymentURL()
	})
}

// SetPaymentQrcode sets the "payment_qrcode" field.
func (u *SubscriptionOrderUpsertBulk) SetPaymentQrcode(v string) *SubscriptionOrderUpsertBulk {
	return u.Update(func(s *SubscriptionOrderUpsert) {
		s.SetPaymentQrcode(v)
	})
}

// UpdatePaymentQrcode sets the "payment_qrcode" field to the value that was provided on create.
func (u *SubscriptionOrderUpsertBulk) UpdatePaymentQrcode() *SubscriptionOrderUpsertBulk {
	return u.Update(func(s *SubscriptionOrderUpsert) {
		s.UpdatePaymentQrcode()
	})
}

// ClearPaymentQrcode clears the value of the "payment_qrcode" field.
func (u *SubscriptionOrderUpsertBulk) ClearPaymentQrcode() *SubscriptionOrderUpsertBulk {
	return u.Update(func(s *SubscriptionOrderUpsert) {
		s.ClearPaymentQrcode()
	})
}

// SetPaymentOpenOrderID sets the "payment_open_order_id" field.
func (u *SubscriptionOrderUpsertBulk) SetPaymentOpenOrderID(v string) *SubscriptionOrderUpsertBulk {
	return u.Update(func(s *SubscriptionOrderUpsert) {
		s.SetPaymentOpenOrderID(v)
	})
}

// UpdatePaymentOpenOrderID sets the "payment_open_order_id" field to the value that was provided on create.
func (u *SubscriptionOrderUpsertBulk) UpdatePaymentOpenOrderID() *SubscriptionOrderUpsertBulk {
	return u.Update(func(s *SubscriptionOrderUpsert) {
		s.UpdatePaymentOpenOrderID()
	})
}

// ClearPaymentOpenOrderID clears the value of the "payment_open_order_id" field.
func (u *SubscriptionOrderUpsertBulk) ClearPaymentOpenOrderID() *SubscriptionOrderUpsertBulk {
	return u.Update(func(s *SubscriptionOrderUpsert) {
		s.ClearPaymentOpenOrderID()
	})
}

// SetPaymentTransactionID sets the "payment_transaction_id" field.
func (u *SubscriptionOrderUpsertBulk) SetPaymentTransactionID(v string) *SubscriptionOrderUpsertBulk {
	return u.Update(func(s *SubscriptionOrderUpsert) {
		s.SetPaymentTransactionID(v)
	})
}

// UpdatePaymentTransactionID sets the "payment_transaction_id" field to the value that was provided on create.
func (u *SubscriptionOrderUpsertBulk) UpdatePaymentTransactionID() *SubscriptionOrderUpsertBulk {
	return u.Update(func(s *SubscriptionOrderUpsert) {
		s.UpdatePaymentTransactionID()
	})
}

// ClearPaymentTransactionID clears the value of the "payment_transaction_id" field.
func (u *SubscriptionOrderUpsertBulk) ClearPaymentTransactionID() *SubscriptionOrderUpsertBulk {
	return u.Update(func(s *SubscriptionOrderUpsert) {
		s.ClearPaymentTransactionID()
	})
}

// SetPaymentPlugin sets the "payment_plugin" field.
func (u *SubscriptionOrderUpsertBulk) SetPaymentPlugin(v string) *SubscriptionOrderUpsertBulk {
	return u.Update(func(s *SubscriptionOrderUpsert) {
		s.SetPaymentPlugin(v)
	})
}

// UpdatePaymentPlugin sets the "payment_plugin" field to the value that was provided on create.
func (u *SubscriptionOrderUpsertBulk) UpdatePaymentPlugin() *SubscriptionOrderUpsertBulk {
	return u.Update(func(s *SubscriptionOrderUpsert) {
		s.UpdatePaymentPlugin()
	})
}

// ClearPaymentPlugin clears the value of the "payment_plugin" field.
func (u *SubscriptionOrderUpsertBulk) ClearPaymentPlugin() *SubscriptionOrderUpsertBulk {
	return u.Update(func(s *SubscriptionOrderUpsert) {
		s.ClearPaymentPlugin()
	})
}

// SetStatus sets the "status" field.
func (u *SubscriptionOrderUpsertBulk) SetStatus(v string) *SubscriptionOrderUpsertBulk {
	return u.Update(func(s *SubscriptionOrderUpsert) {
		s.SetStatus(v)
	})
}

// UpdateStatus sets the "status" field to the value that was provided on create.
func (u *SubscriptionOrderUpsertBulk) UpdateStatus() *SubscriptionOrderUpsertBulk {
	return u.Update(func(s *SubscriptionOrderUpsert) {
		s.UpdateStatus()
	})
}

// SetAmount sets the "amount" field.
func (u *SubscriptionOrderUpsertBulk) SetAmount(v float64) *SubscriptionOrderUpsertBulk {
	return u.Update(func(s *SubscriptionOrderUpsert) {
		s.SetAmount(v)
	})
}

// AddAmount adds v to the "amount" field.
func (u *SubscriptionOrderUpsertBulk) AddAmount(v float64) *SubscriptionOrderUpsertBulk {
	return u.Update(func(s *SubscriptionOrderUpsert) {
		s.AddAmount(v)
	})
}

// UpdateAmount sets the "amount" field to the value that was provided on create.
func (u *SubscriptionOrderUpsertBulk) UpdateAmount() *SubscriptionOrderUpsertBulk {
	return u.Update(func(s *SubscriptionOrderUpsert) {
		s.UpdateAmount()
	})
}

// SetCurrency sets the "currency" field.
func (u *SubscriptionOrderUpsertBulk) SetCurrency(v string) *SubscriptionOrderUpsertBulk {
	return u.Update(func(s *SubscriptionOrderUpsert) {
		s.SetCurrency(v)
	})
}

// UpdateCurrency sets the "currency" field to the value that was provided on create.
func (u *SubscriptionOrderUpsertBulk) UpdateCurrency() *SubscriptionOrderUpsertBulk {
	return u.Update(func(s *SubscriptionOrderUpsert) {
		s.UpdateCurrency()
	})
}

// SetValidityDays sets the "validity_days" field.
func (u *SubscriptionOrderUpsertBulk) SetValidityDays(v int) *SubscriptionOrderUpsertBulk {
	return u.Update(func(s *SubscriptionOrderUpsert) {
		s.SetValidityDays(v)
	})
}

// AddValidityDays adds v to the "validity_days" field.
func (u *SubscriptionOrderUpsertBulk) AddValidityDays(v int) *SubscriptionOrderUpsertBulk {
	return u.Update(func(s *SubscriptionOrderUpsert) {
		s.AddValidityDays(v)
	})
}

// UpdateValidityDays sets the "validity_days" field to the value that was provided on create.
func (u *SubscriptionOrderUpsertBulk) UpdateValidityDays() *SubscriptionOrderUpsertBulk {
	return u.Update(func(s *SubscriptionOrderUpsert) {
		s.UpdateValidityDays()
	})
}

// SetPaidAt sets the "paid_at" field.
func (u *SubscriptionOrderUpsertBulk) SetPaidAt(v time.Time) *SubscriptionOrderUpsertBulk {
	return u.Update(func(s *SubscriptionOrderUpsert) {
		s.SetPaidAt(v)
	})
}

// UpdatePaidAt sets the "paid_at" field to the value that was provided on create.
func (u *SubscriptionOrderUpsertBulk) UpdatePaidAt() *SubscriptionOrderUpsertBulk {
	return u.Update(func(s *SubscriptionOrderUpsert) {
		s.UpdatePaidAt()
	})
}

// ClearPaidAt clears the value of the "paid_at" field.
func (u *SubscriptionOrderUpsertBulk) ClearPaidAt() *SubscriptionOrderUpsertBulk {
	return u.Update(func(s *SubscriptionOrderUpsert) {
		s.ClearPaidAt()
	})
}

// SetCanceledAt sets the "canceled_at" field.
func (u *SubscriptionOrderUpsertBulk) SetCanceledAt(v time.Time) *SubscriptionOrderUpsertBulk {
	return u.Update(func(s *SubscriptionOrderUpsert) {
		s.SetCanceledAt(v)
	})
}

// UpdateCanceledAt sets the "canceled_at" field to the value that was provided on create.
func (u *SubscriptionOrderUpsertBulk) UpdateCanceledAt() *SubscriptionOrderUpsertBulk {
	return u.Update(func(s *SubscriptionOrderUpsert) {
		s.UpdateCanceledAt()
	})
}

// ClearCanceledAt clears the value of the "canceled_at" field.
func (u *SubscriptionOrderUpsertBulk) ClearCanceledAt() *SubscriptionOrderUpsertBulk {
	return u.Update(func(s *SubscriptionOrderUpsert) {
		s.ClearCanceledAt()
	})
}

// SetNotes sets the "notes" field.
func (u *SubscriptionOrderUpsertBulk) SetNotes(v string) *SubscriptionOrderUpsertBulk {
	return u.Update(func(s *SubscriptionOrderUpsert) {
		s.SetNotes(v)
	})
}

// UpdateNotes sets the "notes" field to the value that was provided on create.
func (u *SubscriptionOrderUpsertBulk) UpdateNotes() *SubscriptionOrderUpsertBulk {
	return u.Update(func(s *SubscriptionOrderUpsert) {
		s.UpdateNotes()
	})
}

// ClearNotes clears the value of the "notes" field.
func (u *SubscriptionOrderUpsertBulk) ClearNotes() *SubscriptionOrderUpsertBulk {
	return u.Update(func(s *SubscriptionOrderUpsert) {
		s.ClearNotes()
	})
}

// Exec executes the query.
func (u *SubscriptionOrderUpsertBulk) Exec(ctx context.Context) error {
	if u.create.err != nil {
		return u.create.err
	}
	for i, b := range u.create.builders {
		if len(b.conflict) != 0 {
			return fmt.Errorf("ent: OnConflict was set for builder %d. Set it on the SubscriptionOrderCreateBulk instead", i)
		}
	}
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for SubscriptionOrderCreateBulk.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *SubscriptionOrderUpsertBulk) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}
