// Code generated by ent, DO NOT EDIT.

package ent

import (
	"fmt"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/Wei-Shaw/sub2api/ent/group"
	"github.com/Wei-Shaw/sub2api/ent/subscriptionorder"
	"github.com/Wei-Shaw/sub2api/ent/user"
	"github.com/Wei-Shaw/sub2api/ent/usersubscription"
)

// SubscriptionOrder is the model entity for the SubscriptionOrder schema.
type SubscriptionOrder struct {
	config `json:"-"`
	// ID of the ent.
	ID int64 `json:"id,omitempty"`
	// CreatedAt holds the value of the "created_at" field.
	CreatedAt time.Time `json:"created_at,omitempty"`
	// UpdatedAt holds the value of the "updated_at" field.
	UpdatedAt time.Time `json:"updated_at,omitempty"`
	// OrderNo holds the value of the "order_no" field.
	OrderNo string `json:"order_no,omitempty"`
	// UserID holds the value of the "user_id" field.
	UserID int64 `json:"user_id,omitempty"`
	// GroupID holds the value of the "group_id" field.
	GroupID int64 `json:"group_id,omitempty"`
	// SubscriptionID holds the value of the "subscription_id" field.
	SubscriptionID *int64 `json:"subscription_id,omitempty"`
	// PaymentProvider holds the value of the "payment_provider" field.
	PaymentProvider string `json:"payment_provider,omitempty"`
	// PaymentURL holds the value of the "payment_url" field.
	PaymentURL *string `json:"payment_url,omitempty"`
	// PaymentQrcode holds the value of the "payment_qrcode" field.
	PaymentQrcode *string `json:"payment_qrcode,omitempty"`
	// PaymentOpenOrderID holds the value of the "payment_open_order_id" field.
	PaymentOpenOrderID *string `json:"payment_open_order_id,omitempty"`
	// PaymentTransactionID holds the value of the "payment_transaction_id" field.
	PaymentTransactionID *string `json:"payment_transaction_id,omitempty"`
	// PaymentPlugin holds the value of the "payment_plugin" field.
	PaymentPlugin *string `json:"payment_plugin,omitempty"`
	// Status holds the value of the "status" field.
	Status string `json:"status,omitempty"`
	// Amount holds the value of the "amount" field.
	Amount float64 `json:"amount,omitempty"`
	// Currency holds the value of the "currency" field.
	Currency string `json:"currency,omitempty"`
	// ValidityDays holds the value of the "validity_days" field.
	ValidityDays int `json:"validity_days,omitempty"`
	// PaidAt holds the value of the "paid_at" field.
	PaidAt *time.Time `json:"paid_at,omitempty"`
	// CanceledAt holds the value of the "canceled_at" field.
	CanceledAt *time.Time `json:"canceled_at,omitempty"`
	// Notes holds the value of the "notes" field.
	Notes *string `json:"notes,omitempty"`
	// Edges holds the relations/edges for other nodes in the graph.
	// The values are being populated by the SubscriptionOrderQuery when eager-loading is set.
	Edges        SubscriptionOrderEdges `json:"edges"`
	selectValues sql.SelectValues
}

// SubscriptionOrderEdges holds the relations/edges for other nodes in the graph.
type SubscriptionOrderEdges struct {
	// User holds the value of the user edge.
	User *User `json:"user,omitempty"`
	// Group holds the value of the group edge.
	Group *Group `json:"group,omitempty"`
	// Subscription holds the value of the subscription edge.
	Subscription *UserSubscription `json:"subscription,omitempty"`
	// loadedTypes holds the information for reporting if a
	// type was loaded (or requested) in eager-loading or not.
	loadedTypes [3]bool
}

// UserOrErr returns the User value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e SubscriptionOrderEdges) UserOrErr() (*User, error) {
	if e.User != nil {
		return e.User, nil
	} else if e.loadedTypes[0] {
		return nil, &NotFoundError{label: user.Label}
	}
	return nil, &NotLoadedError{edge: "user"}
}

// GroupOrErr returns the Group value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e SubscriptionOrderEdges) GroupOrErr() (*Group, error) {
	if e.Group != nil {
		return e.Group, nil
	} else if e.loadedTypes[1] {
		return nil, &NotFoundError{label: group.Label}
	}
	return nil, &NotLoadedError{edge: "group"}
}

// SubscriptionOrErr returns the Subscription value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e SubscriptionOrderEdges) SubscriptionOrErr() (*UserSubscription, error) {
	if e.Subscription != nil {
		return e.Subscription, nil
	} else if e.loadedTypes[2] {
		return nil, &NotFoundError{label: usersubscription.Label}
	}
	return nil, &NotLoadedError{edge: "subscription"}
}

// scanValues returns the types for scanning values from sql.Rows.
func (*SubscriptionOrder) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case subscriptionorder.FieldAmount:
			values[i] = new(sql.NullFloat64)
		case subscriptionorder.FieldID, subscriptionorder.FieldUserID, subscriptionorder.FieldGroupID, subscriptionorder.FieldSubscriptionID, subscriptionorder.FieldValidityDays:
			values[i] = new(sql.NullInt64)
		case subscriptionorder.FieldOrderNo, subscriptionorder.FieldPaymentProvider, subscriptionorder.FieldPaymentURL, subscriptionorder.FieldPaymentQrcode, subscriptionorder.FieldPaymentOpenOrderID, subscriptionorder.FieldPaymentTransactionID, subscriptionorder.FieldPaymentPlugin, subscriptionorder.FieldStatus, subscriptionorder.FieldCurrency, subscriptionorder.FieldNotes:
			values[i] = new(sql.NullString)
		case subscriptionorder.FieldCreatedAt, subscriptionorder.FieldUpdatedAt, subscriptionorder.FieldPaidAt, subscriptionorder.FieldCanceledAt:
			values[i] = new(sql.NullTime)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the SubscriptionOrder fields.
func (_m *SubscriptionOrder) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case subscriptionorder.FieldID:
			value, ok := values[i].(*sql.NullInt64)
			if !ok {
				return fmt.Errorf("unexpected type %T for field id", value)
			}
			_m.ID = int64(value.Int64)
		case subscriptionorder.FieldCreatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field created_at", values[i])
			} else if value.Valid {
				_m.CreatedAt = value.Time
			}
		case subscriptionorder.FieldUpdatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field updated_at", values[i])
			} else if value.Valid {
				_m.UpdatedAt = value.Time
			}
		case subscriptionorder.FieldOrderNo:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field order_no", values[i])
			} else if value.Valid {
				_m.OrderNo = value.String
			}
		case subscriptionorder.FieldUserID:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field user_id", values[i])
			} else if value.Valid {
				_m.UserID = value.Int64
			}
		case subscriptionorder.FieldGroupID:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field group_id", values[i])
			} else if value.Valid {
				_m.GroupID = value.Int64
			}
		case subscriptionorder.FieldSubscriptionID:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field subscription_id", values[i])
			} else if value.Valid {
				_m.SubscriptionID = new(int64)
				*_m.SubscriptionID = value.Int64
			}
		case subscriptionorder.FieldPaymentProvider:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field payment_provider", values[i])
			} else if value.Valid {
				_m.PaymentProvider = value.String
			}
		case subscriptionorder.FieldPaymentURL:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field payment_url", values[i])
			} else if value.Valid {
				_m.PaymentURL = new(string)
				*_m.PaymentURL = value.String
			}
		case subscriptionorder.FieldPaymentQrcode:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field payment_qrcode", values[i])
			} else if value.Valid {
				_m.PaymentQrcode = new(string)
				*_m.PaymentQrcode = value.String
			}
		case subscriptionorder.FieldPaymentOpenOrderID:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field payment_open_order_id", values[i])
			} else if value.Valid {
				_m.PaymentOpenOrderID = new(string)
				*_m.PaymentOpenOrderID = value.String
			}
		case subscriptionorder.FieldPaymentTransactionID:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field payment_transaction_id", values[i])
			} else if value.Valid {
				_m.PaymentTransactionID = new(string)
				*_m.PaymentTransactionID = value.String
			}
		case subscriptionorder.FieldPaymentPlugin:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field payment_plugin", values[i])
			} else if value.Valid {
				_m.PaymentPlugin = new(string)
				*_m.PaymentPlugin = value.String
			}
		case subscriptionorder.FieldStatus:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field status", values[i])
			} else if value.Valid {
				_m.Status = value.String
			}
		case subscriptionorder.FieldAmount:
			if value, ok := values[i].(*sql.NullFloat64); !ok {
				return fmt.Errorf("unexpected type %T for field amount", values[i])
			} else if value.Valid {
				_m.Amount = value.Float64
			}
		case subscriptionorder.FieldCurrency:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field currency", values[i])
			} else if value.Valid {
				_m.Currency = value.String
			}
		case subscriptionorder.FieldValidityDays:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field validity_days", values[i])
			} else if value.Valid {
				_m.ValidityDays = int(value.Int64)
			}
		case subscriptionorder.FieldPaidAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field paid_at", values[i])
			} else if value.Valid {
				_m.PaidAt = new(time.Time)
				*_m.PaidAt = value.Time
			}
		case subscriptionorder.FieldCanceledAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field canceled_at", values[i])
			} else if value.Valid {
				_m.CanceledAt = new(time.Time)
				*_m.CanceledAt = value.Time
			}
		case subscriptionorder.FieldNotes:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field notes", values[i])
			} else if value.Valid {
				_m.Notes = new(string)
				*_m.Notes = value.String
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the SubscriptionOrder.
// This includes values selected through modifiers, order, etc.
func (_m *SubscriptionOrder) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// QueryUser queries the "user" edge of the SubscriptionOrder entity.
func (_m *SubscriptionOrder) QueryUser() *UserQuery {
	return NewSubscriptionOrderClient(_m.config).QueryUser(_m)
}

// QueryGroup queries the "group" edge of the SubscriptionOrder entity.
func (_m *SubscriptionOrder) QueryGroup() *GroupQuery {
	return NewSubscriptionOrderClient(_m.config).QueryGroup(_m)
}

// QuerySubscription queries the "subscription" edge of the SubscriptionOrder entity.
func (_m *SubscriptionOrder) QuerySubscription() *UserSubscriptionQuery {
	return NewSubscriptionOrderClient(_m.config).QuerySubscription(_m)
}

// Update returns a builder for updating this SubscriptionOrder.
// Note that you need to call SubscriptionOrder.Unwrap() before calling this method if this SubscriptionOrder
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *SubscriptionOrder) Update() *SubscriptionOrderUpdateOne {
	return NewSubscriptionOrderClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the SubscriptionOrder entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *SubscriptionOrder) Unwrap() *SubscriptionOrder {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: SubscriptionOrder is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *SubscriptionOrder) String() string {
	var builder strings.Builder
	builder.WriteString("SubscriptionOrder(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("created_at=")
	builder.WriteString(_m.CreatedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("updated_at=")
	builder.WriteString(_m.UpdatedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("order_no=")
	builder.WriteString(_m.OrderNo)
	builder.WriteString(", ")
	builder.WriteString("user_id=")
	builder.WriteString(fmt.Sprintf("%v", _m.UserID))
	builder.WriteString(", ")
	builder.WriteString("group_id=")
	builder.WriteString(fmt.Sprintf("%v", _m.GroupID))
	builder.WriteString(", ")
	if v := _m.SubscriptionID; v != nil {
		builder.WriteString("subscription_id=")
		builder.WriteString(fmt.Sprintf("%v", *v))
	}
	builder.WriteString(", ")
	builder.WriteString("payment_provider=")
	builder.WriteString(_m.PaymentProvider)
	builder.WriteString(", ")
	if v := _m.PaymentURL; v != nil {
		builder.WriteString("payment_url=")
		builder.WriteString(*v)
	}
	builder.WriteString(", ")
	if v := _m.PaymentQrcode; v != nil {
		builder.WriteString("payment_qrcode=")
		builder.WriteString(*v)
	}
	builder.WriteString(", ")
	if v := _m.PaymentOpenOrderID; v != nil {
		builder.WriteString("payment_open_order_id=")
		builder.WriteString(*v)
	}
	builder.WriteString(", ")
	if v := _m.PaymentTransactionID; v != nil {
		builder.WriteString("payment_transaction_id=")
		builder.WriteString(*v)
	}
	builder.WriteString(", ")
	if v := _m.PaymentPlugin; v != nil {
		builder.WriteString("payment_plugin=")
		builder.WriteString(*v)
	}
	builder.WriteString(", ")
	builder.WriteString("status=")
	builder.WriteString(_m.Status)
	builder.WriteString(", ")
	builder.WriteString("amount=")
	builder.WriteString(fmt.Sprintf("%v", _m.Amount))
	builder.WriteString(", ")
	builder.WriteString("currency=")
	builder.WriteString(_m.Currency)
	builder.WriteString(", ")
	builder.WriteString("validity_days=")
	builder.WriteString(fmt.Sprintf("%v", _m.ValidityDays))
	builder.WriteString(", ")
	if v := _m.PaidAt; v != nil {
		builder.WriteString("paid_at=")
		builder.WriteString(v.Format(time.ANSIC))
	}
	builder.WriteString(", ")
	if v := _m.CanceledAt; v != nil {
		builder.WriteString("canceled_at=")
		builder.WriteString(v.Format(time.ANSIC))
	}
	builder.WriteString(", ")
	if v := _m.Notes; v != nil {
		builder.WriteString("notes=")
		builder.WriteString(*v)
	}
	builder.WriteByte(')')
	return builder.String()
}

// SubscriptionOrders is a parsable slice of SubscriptionOrder.
type SubscriptionOrders []*SubscriptionOrder
